// Generated by Copilot
// DEBUG: Log some class_subjects rows (guarded in production)
export async function logAllClassSubjects(limit: number = 100) {
  // Disable this debug function in production builds
  if (import.meta.env && import.meta.env.MODE === 'production') {
    console.warn('logAllClassSubjects is disabled in production');
    return [];
  }

  const from = 0;
  const to = Math.max(0, limit - 1);
  const { data, error } = await supabase.from('class_subjects').select('*').range(from, to);
  if (error) {
    console.error('Error fetching class_subjects:', error);
    return [];
  }
  console.log(`class_subjects rows (first ${limit}):`, data);
  return data || [];
}
// Get all class/subject assignments for a teacher
export async function getClassAssignmentsForTeacher(teacherId: string): Promise<{ className: string, subjectId: string }[]> {
  const { data, error } = await supabase
    .from('class_subjects')
    .select('className, subjectId')
    .eq('teacherId', teacherId);
  if (error) return [];
  return data || [];
}
import { User, Student, Exam, ExamStatus, ExamType, Role, AcademicYear, Term, Subject, GradeScale, ReportConfig, MonthlyScore, MidtermReport, FinalReport, getGrade } from '../types';
import { supabase } from './supabase';

// ── Authentication ──
export async function signIn(email: string, password: string) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });
  if (error) throw error;
  return data;
}

// Sign up a new user (used for first-time password setup)
export async function signUp(email: string, password: string) {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });
  if (error) throw error;
  // Create user profile in our users table
  if (data.user) {
    const { error: profileError } = await supabase
      .from('users')
      .update({ id: data.user.id })
      .eq('email', email);
    if (profileError) throw profileError;
  }
  return data;
}

// ...existing code...

// Helper: check if user exists in Supabase Auth
export async function isUserInAuth(email: string): Promise<boolean> {
  // Supabase does not provide direct API to check, so try signIn with random password
  const { error } = await supabase.auth.signInWithPassword({ email, password: 'invalid-password' });
  if (error && error.message.includes('Invalid login credentials')) {
    // If error is invalid credentials, user exists in Auth
    return true;
  }
  // If error is user not found, user does not exist
  return false;
}

export async function signOut() {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
}

export async function getCurrentUser() {
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error) throw error;
  return user;
}

export async function getCurrentUserProfile() {
  const user = await getCurrentUser();
  if (!user) return null;

  const { data, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', user.id)
    .maybeSingle();

  if (error) throw error;
  return data;
}

export async function createDemoAccounts() {
  const demoUsers = [
    { email: 'admin@scholo.com', password: 'admin123', name: 'Dr. Sarah Mitchell', role: 'admin' as const },
    { email: 'teacher@scholo.com', password: 'teacher123', name: 'Prof. James Wilson', role: 'teacher' as const, assignedClasses: ['Grade 10-A', 'Grade 9-A', 'Grade 8-B'], assignedSubjects: ['Mathematics', 'English', 'Science'] },
    { email: 'parent@scholo.com', password: 'parent123', name: 'Michael Johnson', role: 'parent' as const },
  ];

  for (const user of demoUsers) {
    try {
      // Check if user already exists
      const { data: existing } = await supabase
        .from('users')
        .select('id')
        .eq('email', user.email)
        .maybeSingle();

      if (existing) {
        console.log(`Demo account for ${user.email} already exists`);
        continue; // Skip if already exists
      }

      // For demo purposes, create user profile directly with a generated ID
      // In production, you'd use proper authentication
      const userId = `${user.role}-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;

      const { error: profileError } = await supabase
        .from('users')
        .insert({
          id: userId,
          email: user.email,
          name: user.name,
          role: user.role,
          assignedClasses: user.assignedClasses || [],
        });

      if (profileError) throw profileError;

      console.log(`Created demo account for ${user.email}`);
    } catch (error) {
      console.error(`Error creating demo account for ${user.email}:`, error);
    }
  }
}

// ── Users ──
export async function getUsers(page: number = 1, limit: number = 100): Promise<User[]> {
  // Prefer the paginated helper to avoid unbounded full-table loads
  const result = await getUsersPaginated(page, limit);
  return result.users;
}

export async function getUsersPaginated(page: number = 1, limit: number = 10, search?: string): Promise<{ users: User[], total: number }> {
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase
    .from('users')
    .select('*', { count: 'exact' });

  if (search && search.trim()) {
    query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
  }

  const { data, error, count } = await query.range(from, to);

  if (error) throw error;
  return { users: data || [], total: count || 0 };
}

export async function getUsersByRole(role: Role, page: number = 1, limit: number = 100): Promise<User[]> {
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  const { data, error } = await supabase.from('users').select('*', { count: 'exact' }).eq('role', role).range(from, to);
  if (error) throw error;
  return data || [];
}

export async function getUserById(id: string): Promise<User | undefined> {
  const { data, error } = await supabase.from('users').select('*').eq('id', id).single();
  if (error) return undefined;
  return data;
}

export async function createUser(data: Omit<User, 'id' | 'createdAt'>): Promise<User> {
  // Generate unique ID based on role and timestamp
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  const id = `${data.role}-${timestamp}-${random}`;

  const user: Omit<User, 'id'> = { ...data, createdAt: new Date().toISOString() };
  const { data: created, error } = await supabase.from('users').insert({ id, ...user }).select().single();
  if (error) {
    console.error('Error creating user:', error);
    throw error;
  }
  return created;
}

export async function updateUser(id: string, data: Partial<User>): Promise<User | null> {
  const { data: updated, error } = await supabase.from('users').update(data).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

export async function deleteUser(id: string): Promise<boolean> {
  const { error } = await supabase.from('users').delete().eq('id', id);
  if (error) return false;
  // Also unlink students from deleted parent
  await supabase.from('students').update({ parentid: null }).eq('parentid', id);
  return true;
}

// ── New Schema Functions ──
export async function getAcademicYears(): Promise<AcademicYear[]> {
  const { data, error } = await supabase.from('academic_years').select('*');
  if (error) throw error;
  return data || [];
}

export async function getCurrentTerm(): Promise<Term | null> {
  const { data, error } = await supabase
    .from('terms')
    .select('*, academic_years(*)')
    .eq('isCurrent', true)
    .single();
  if (error) return null;
  return data;
}

export async function getSubjects(): Promise<Subject[]> {
  const { data, error } = await supabase.from('subjects').select('*');
  if (error) throw error;
  return data || [];
}

export async function getGradeScales(): Promise<GradeScale[]> {
  const { data, error } = await supabase.from('grade_scales').select('*');
  if (error) throw error;
  return data || [];
}

export async function getReportConfig(): Promise<ReportConfig> {
  const { data, error } = await supabase
    .from('report_config')
    .select('*')
    .eq('id', 'default')
    .single();
  if (error) throw error;
  return data;
}

// RPC functions for reports
export async function getMonthlyReport(
  studentId: string,
  termId: string
): Promise<MonthlyScore[]> {
  const { data, error } = await supabase.rpc('get_monthly_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });
  if (error) throw error;
  return data;
}

export async function getMidtermReport(
  studentId: string,
  termId: string
): Promise<MidtermReport> {
  const { data, error } = await supabase.rpc('get_midterm_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });

  if (!error) return data;

  // Fallback when RPC function does not exist (404/PGRST202)
  if (error.code === 'PGRST202' || (error.details && error.details.includes('get_midterm_report'))) {
    return getMidtermReportFallback(studentId, termId);
  }

  throw error;
}

async function getMidtermReportFallback(studentId: string, termId: string): Promise<MidtermReport> {
  const student = await getStudentById(studentId);
  if (!student) {
    return { scores: [], overall_rank: 0, total_students: 0 };
  }

const { data: studentExams, error: studentError } = await supabase
  .from('exams')
  .select('*')
  .eq('studentId', studentId)
  .eq('termId', termId)
  .eq('examType', 'Midterm')
  .eq('status', 'approved')
  .returns<Exam[]>();
  if (studentError) throw studentError;

const { data: classStudents, error: classError } = await supabase
  .from('students')
  .select('id')
  .eq('className', student.className)
  .returns<{ id: string }[]>();
  if (classError) throw classError;

  const classStudentIds = classStudents?.map(s => s.id) ?? [];

  const { data: classExams, error: classExamsError } = await supabase
  .from('exams')
  .select('*')
  .in('studentId', classStudentIds)
  .eq('termId', termId)
  .eq('examType', 'Midterm')
  .eq('status', 'approved')
  .returns<Exam[]>();
  if (classExamsError) throw classExamsError;

  const bySubject = new Map<string, MidtermScore>();

  for (const e of studentExams ?? []) {
    const percentage = e.total > 0 ? Math.round((e.score / e.total) * 100) : 0;
    const grade = getGrade(percentage);
    const remark = grade === 'A' ? 'Excellent' : grade === 'B' ? 'Very Good' : grade === 'C' ? 'Good' : grade === 'D' ? 'Satisfactory' : 'Needs Improvement';

    const sameSubjectClass = (classExams ?? []).filter(ex => ex.subject === e.subject);
    const classAvg = sameSubjectClass.length
      ? Math.round(sameSubjectClass.reduce((sum, ex) => sum + (ex.total > 0 ? (ex.score / ex.total) * 100 : 0), 0) / sameSubjectClass.length)
      : 0;

    const highestInClass = sameSubjectClass.length
      ? Math.max(...sameSubjectClass.map(ex => (ex.total > 0 ? Math.round((ex.score / ex.total) * 100) : 0)))
      : 0;

    const sortedSubject = [...sameSubjectClass]
      .map(ex => (ex.total > 0 ? Math.round((ex.score / ex.total) * 100) : 0))
      .sort((a, b) => b - a);

    const subjectRank = sortedSubject.indexOf(percentage) + 1;

    bySubject.set(e.subject, {
      subject: e.subject,
      score: e.score,
      total: e.total,
      percentage,
      grade,
      remark,
      subject_rank: subjectRank || 1,
      class_average: classAvg,
      highest_in_class: highestInClass,
      examId: e.id,
    });
  }

  const scores = Array.from(bySubject.values());

  const studentAverage = scores.length
    ? Math.round(scores.reduce((sum, s) => sum + s.percentage, 0) / scores.length)
    : 0;

  const classAverages = new Map<string, number>();
  for (const sid of classStudentIds) {
    const exams = (classExams ?? []).filter(ex => ex.studentId === sid);
    const pct = exams.length
      ? Math.round(exams.reduce((sum, ex) => sum + (ex.total > 0 ? (ex.score / ex.total) * 100 : 0), 0) / exams.length)
      : 0;
    classAverages.set(sid, pct);
  }

  const sortedClassAverages = [...classAverages.values()].sort((a, b) => b - a);
  const overall_rank = sortedClassAverages.indexOf(studentAverage) + 1;
  const total_students = classAverages.size;

  return { scores, overall_rank: overall_rank || 0, total_students };
}

export async function getFinalReport(
  studentId: string,
  termId: string
): Promise<FinalReport> {
  const { data, error } = await supabase.rpc('get_final_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });
  if (error) throw error;
  return data;
}

// ── Students ──
export async function getStudents(page: number = 1, limit: number = 50): Promise<Student[]> {
  const result = await getStudentsPaginated(page, limit);
  return result.students;
}

export async function getStudentsPaginated(page: number = 1, limit: number = 50, search?: string): Promise<{ students: Student[], total: number }> {
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase
    .from('students')
    .select('*', { count: 'exact' });

  if (search && search.trim()) {
    query = query.ilike('name', `%${search}%`);
  }

  const { data, error, count } = await query.range(from, to);

  if (error) throw error;
  return { students: data || [], total: count || 0 };
}

export async function getStudentById(id: string): Promise<Student | undefined> {
  const { data, error } = await supabase.from('students').select('*').eq('id', id).single();
  if (error) return undefined;
  return data;
}

export async function getStudentsByParent(parentId: string): Promise<Student[]> {
  const { data, error } = await supabase.from('students').select('*').eq('parentId', parentId);
  if (error) throw error;
  return data || [];
}


export async function getStudentsByClass(className: string): Promise<Student[]> {
  const { data, error } = await supabase.from('students').select('*').eq('className', className);
  if (error) throw error;
  return data || [];
}

export async function getStudentsByClasses(classnames: string[], search?: string): Promise<Student[]> {
  let query = supabase.from('students').select('*');
  if (classnames && classnames.length > 0) {
    query = query.in('className', classnames);
  }
  if (search && search.trim()) {
    query = query.ilike('name', `%${search}%`);
  }
  const { data, error } = await query;
  if (error) throw error;
  return data || [];
}

// Return distinct list of classes from students table
export async function getClasses(): Promise<string[]> {
  const { data, error } = await supabase.from('students').select('className');
  if (error) throw error;
  const classes = Array.from(new Set((data || []).map((r: any) => r.className).filter(Boolean)));
  classes.sort();
  return classes;
}




// ── Subjects ──
export async function getSubjectById(id: string): Promise<Subject | null> {
  const { data, error } = await supabase.from('subjects').select('*').eq('id', id).single();
  if (error) return null;
  return data;
}

export async function createSubject(data: Omit<Subject, 'id' | 'createdAt'>): Promise<Subject> {
  const timestamp = Date.now();
  const id = `subject-${timestamp}-${Math.random().toString(36).slice(2, 8)}`;
  const item = { id, ...data, createdAt: new Date().toISOString() };
  const { data: created, error } = await supabase.from('subjects').insert(item).select().single();
  if (error) throw error;
  return created;
}

export async function updateSubject(id: string, data: Partial<Subject>): Promise<Subject | null> {
  const { data: updated, error } = await supabase.from('subjects').update(data).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

export async function deleteSubject(id: string): Promise<boolean> {
  const { error } = await supabase.from('subjects').delete().eq('id', id);
  return !error;
}

// ── Academic Years ──
export async function createAcademicYear(data: Omit<AcademicYear, 'id' | 'createdAt'>): Promise<AcademicYear> {
  const timestamp = Date.now();
  const id = `year-${timestamp}-${Math.random().toString(36).slice(2, 8)}`;
  const item = { id, ...data, createdAt: new Date().toISOString() };
  const { data: created, error } = await supabase.from('academic_years').insert(item).select().single();
  if (error) throw error;
  return created;
}

export async function updateAcademicYear(id: string, data: Partial<AcademicYear>): Promise<AcademicYear | null> {
  const { data: updated, error } = await supabase.from('academic_years').update(data).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

export async function deleteAcademicYear(id: string): Promise<boolean> {
  const { error } = await supabase.from('academic_years').delete().eq('id', id);
  return !error;
}

// ── Terms ──
export async function getTerms(): Promise<Term[]> {
  const { data, error } = await supabase.from('terms').select('*, academic_years(*)').order('startDate', { ascending: false });
  if (error) throw error;
  return data || [];
}

export async function createTerm(data: Omit<Term, 'id' | 'createdAt' | 'months'>): Promise<Term> {
  const timestamp = Date.now();
  const id = `term-${timestamp}-${Math.random().toString(36).slice(2, 8)}`;
  const item = { id, ...data, months: data.months || [], createdAt: new Date().toISOString() };
  const { data: created, error } = await supabase.from('terms').insert(item).select().single();
  if (error) throw error;
  return created;
}
export async function updateTerm(id: string, data: Partial<Term>): Promise<Term | null> {
  const { data: updated, error } = await supabase.from('terms').update(data).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

export async function deleteTerm(id: string): Promise<boolean> {
  const { error } = await supabase.from('terms').delete().eq('id', id);
  return !error;
}

export async function createStudent(data: Omit<Student, 'id' | 'createdAt'>): Promise<Student> {
  // Generate unique ID
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  const id = `student-${timestamp}-${random}`;

  // Use PascalCase for DB columns to match Supabase schema
  const student = {
    name: data.name,
    className: data.className,
    parentId: data.parentId,
    createdAt: new Date().toISOString(),
  };
  const { data: created, error } = await supabase.from('students').insert({ id, ...student }).select().single();
  if (error) throw error;
  return created;
}

export async function updateStudent(id: string, data: Partial<Student>): Promise<Student | null> {
  // Use PascalCase for DB columns to match Supabase schema
  const updateData: any = {};
  if (data.name !== undefined) updateData.name = data.name;
  if (data.className !== undefined) updateData.className = data.className;
  if (data.parentId !== undefined) updateData.parentId = data.parentId;
  if (data.createdAt !== undefined) updateData.createdAt = data.createdAt;
  const { data: updated, error } = await supabase.from('students').update(updateData).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

export async function deleteStudent(id: string): Promise<boolean> {
  const { error } = await supabase.from('students').delete().eq('id', id);
  if (error) return false;
  await supabase.from('exams').delete().eq('studentid', id);
  return true;
}

// ── Exams ──
export async function getExams(): Promise<Exam[]> {
  const { data, error } = await supabase.from('exams').select('*');
  if (error) throw error;
  return data || [];
}

export async function getExamsByStudent(studentId: string): Promise<Exam[]> {
  const { data, error } = await supabase.from('exams').select('*').eq('studentId', studentId);
  if (error) throw error;
  return data || [];
}

export async function getExamsByParent(parentId: string, statusFilter?: ExamStatus): Promise<Exam[]> {
  let query = supabase.from('exams').select('*').eq('parentId', parentId);
  if (statusFilter) query = query.eq('status', statusFilter);
  const { data, error } = await query;
  if (error) throw error;
  return data || [];
}

export async function getExamsByTeacher(teacherId: string): Promise<Exam[]> {
  const { data, error } = await supabase.from('exams').select('*').eq('teacherId', teacherId);
  if (error) throw error;
  return data || [];
}

export async function getExamsByStatus(status: ExamStatus): Promise<Exam[]> {
  const { data, error } = await supabase.from('exams').select('*').eq('status', status);
  if (error) throw error;
  return data || [];
}

export async function createExam(data: Omit<Exam, 'id' | 'created_At'>): Promise<Exam> {
  // Generate unique ID
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  const id = `exam-${timestamp}-${random}`;

  const exam: Omit<Exam, 'id'> = { ...data, createdAt: new Date().toISOString() };
  const { data: created, error } = await supabase.from('exams').insert({ id, ...exam }).select().single();
  if (error) throw error;
  return created;
}

export async function updateExamStatus(id: string, status: ExamStatus): Promise<Exam | null> {
  const { data: updated, error } = await supabase.from('exams').update({ status }).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

// Approve all exams currently pending
export async function approveAllPendingExams(): Promise<Exam[] | null> {
  const { data, error } = await supabase.from('exams').update({ status: 'approved' }).eq('status', 'pending').select();
  if (error) return null;
  return data || [];
}

export async function approvePendingExamsForClasses(classNames: string[]): Promise<Exam[] | null> {
  if (!Array.isArray(classNames) || classNames.length === 0) return [];

  const students = await getStudentsByClasses(classNames);
  const studentIds = students.map(s => s.id);
  if (studentIds.length === 0) return [];

  const { data, error } = await supabase
    .from('exams')
    .update({ status: 'approved' })
    .in('studentId', studentIds)
    .eq('status', 'pending')
    .select();

  if (error) return null;
  return data || [];
}

// Allow admin to edit an exam record
export async function updateExam(id: string, data: Partial<Exam>): Promise<Exam | null> {
  const { data: updated, error } = await supabase.from('exams').update(data).eq('id', id).select().single();
  if (error) return null;
  return updated;
}

// Report comments (teacher/principal remarks)
export async function getReportComment(studentId: string, termId: string, examId?: string): Promise<ReportComment | null> {
  let query = supabase.from('report_comments').select('*');
  if (examId) query = query.eq('examId', examId);
  else query = query.eq('studentId', studentId).eq('termId', termId);
  const { data, error } = await query.maybeSingle();
  if (error) return null;
  return data || null;
}

export async function upsertReportComment(comment: Omit<ReportComment, 'id' | 'createdAt'>): Promise<ReportComment | null> {
  // Always check for existing by studentId, termId, and examId (all required for unique comment per subject)
  if (!comment.examId) {
    throw new Error('examId is required to allow multiple comments for different subjects.');
  }
  const { data: existingRows, error: findError } = await supabase
    .from('report_comments')
    .select('*')
    .eq('studentId', comment.studentId)
    .eq('termId', comment.termId)
    .eq('examId', comment.examId);
  if (findError) return null;
  const existing = (existingRows && existingRows.length > 0) ? existingRows[0] : null;

  if (existing && existing.id) {
    const { data, error } = await supabase.from('report_comments').update(comment).eq('id', existing.id).select().single();
    if (error) return null;
    return data || null;
  }

  const id = `rc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const item = { id, ...comment, createdAt: new Date().toISOString() } as any;
  const { data, error } = await supabase.from('report_comments').insert(item).select().single();
  if (error) return null;
  return data || null;
}

// Return subjects for a class optionally filtered by teacher assignment
export async function getClassSubjectsForTeacher(teacherId?: string, className?: string): Promise<Subject[]> {
  // Attempt to join class_subjects -> subjects
  let query = supabase.from('class_subjects').select('subjectId, teacherId, className, subjects(*)');
  if (teacherId) query = query.eq('teacherId', teacherId);
  if (className) query = query.eq('className', className);
  const { data, error } = await query;
  if (error) return [];
  const rows: any[] = data || [];
  const subjects = rows.map(r => r.subjects).filter(Boolean) as Subject[];
  return subjects;
}

// CRUD for class_subjects
export async function getClassSubjects(): Promise<any[]> {
  const { data, error } = await supabase.from('class_subjects').select('id, className, teacherId, subjectId, subjects(name), users(name)');
  if (error) return [];
  return data || [];
}

export async function createClassSubject(item: { className: string; subjectId: string; teacherId?: string }) {
  const id = `cs-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const payload = { id, ...item, createdAt: new Date().toISOString() } as any;
  const { data, error } = await supabase.from('class_subjects').insert(payload).select().single();
  if (error) throw error;
  return data;
}

export async function updateClassSubject(id: string, dataObj: Partial<{ className: string; subjectId: string; teacherId?: string }>) {
  const { data, error } = await supabase.from('class_subjects').update(dataObj).eq('id', id).select().single();
  if (error) throw error;
  return data;
}

export async function deleteClassSubject(id: string) {
  const { error } = await supabase.from('class_subjects').delete().eq('id', id);
  if (error) throw error;
  return true;
}

// Fetch all report comments for a student & term
export async function getReportCommentsForStudentTerm(studentId: string, termId: string): Promise<ReportComment[]> {
  const { data, error } = await supabase.from('report_comments').select('*').eq('studentId', studentId).eq('termId', termId);
  if (error) return [];
  return data || [];
}

// Update the report configuration (admin only)
export async function updateReportConfig(data: Partial<ReportConfig>): Promise<ReportConfig | null> {
  const { data: updated, error } = await supabase.from('report_config').update(data).eq('id', 'default').select().single();
  if (error) return null;
  return updated;
}

export async function deleteExam(id: string): Promise<boolean> {
  const { error } = await supabase.from('exams').delete().eq('id', id);
  return !error;
}

// ── Bulk Operations ──
export async function bulkCreateUsers(dataList: Omit<User, 'id' | 'createdAt'>[]): Promise<User[]> {
  const users = dataList.map(data => {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 8);
    const id = `${data.role}-${timestamp}-${random}`;
    return { id, ...data, createdAt: new Date().toISOString() };
  });
  const { data, error } = await supabase.from('users').insert(users).select();
  if (error) throw error;
  return data || [];
}

export async function bulkCreateStudents(dataList: Omit<Student, 'id' | 'createdAt'>[]): Promise<Student[]> {
  const studentsWithTimestamps = dataList.map(data => {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 8);
    const id = `student-${timestamp}-${random}`;
    return { id, ...data, createdAt: new Date().toISOString() };
  });
  const { data, error } = await supabase.from('students').insert(studentsWithTimestamps).select();
  if (error) throw error;
  return data || [];
}

export async function bulkCreateExams(dataList: Omit<Exam, 'id' | 'createdAt'>[]): Promise<Exam[]> {
  const examsWithTimestamps = dataList.map(data => {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 8);
    const id = `exam-${timestamp}-${random}`;
    return { id, ...data, createdAt: new Date().toISOString() };
  });
  const { data, error } = await supabase.from('exams').insert(examsWithTimestamps).select();
  if (error) throw error;
  return data || [];
}

// ── Stats ──
export async function getSystemStats() {
  const [users, students, exams] = await Promise.all([
    getUsers(),
    getStudents(),
    getExams()
  ]);

  return {
    totalTeachers: users.filter(u => u.role === 'teacher').length,
    totalParents: users.filter(u => u.role === 'parent').length,
    totalStudents: students.length,
    totalExams: exams.length,
    pendingExams: exams.filter(e => e.status === 'pending').length,
    approvedExams: exams.filter(e => e.status === 'approved').length,
    rejectedExams: exams.filter(e => e.status === 'rejected').length,
    averageScore: exams.length > 0
      ? Math.round(exams.reduce((sum, e) => sum + (e.score / e.total) * 100, 0) / exams.length)
      : 0,
  };
}

// ── Seeding ──
export async function isSeeded(): Promise<boolean> {
  const users = await getUsers();
  return users.length > 0;
}

export async function seedDatabase(): Promise<void> {
  // Clear existing data
  await supabase.from('exams').delete().neq('id', ''); // Delete all
  await supabase.from('students').delete().neq('id', '');
  await supabase.from('users').delete().neq('id', '');

  const now = new Date().toISOString();

  // Users
  const admin: User = {
    id: 'admin-001', name: 'Dr. Sarah Mitchell', email: 'admin@campus.edu',
    role: 'admin', createdAt: now,
  };

  const teacher1: User = {
    id: 'teacher-001', name: 'Prof. James Wilson', email: 'jwilson@campus.edu',
    role: 'teacher', assignedClasses: ['Grade 10-A', 'Grade 9-A', 'Grade 8-B'],
    createdAt: now,
  };

  const teacher2: User = {
    id: 'teacher-002', name: 'Ms. Emily Chen', email: 'echen@campus.edu',
    role: 'teacher', assignedClasses: ['Grade 7-C', 'Grade 10-A'],
    createdAt: now,
  };

  const parent1: User = {
    id: 'parent-001', name: 'Michael Johnson', email: 'mjohnson@email.com',
    role: 'parent', phone1: '0612345678', phone2: '0612345679',
    xafada: 'Hodan', udow: 'Bakaaraha', 
    createdAt: now,
  };

  const parent2: User = {
    id: 'parent-002', name: 'Lisa Rodriguez', email: 'lrodriguez@email.com',
    role: 'parent', phone1: '0617654321', phone2: '0617654322',
    xafada: 'Warta Nabadda', udow: 'Km4 Junction',
createdAt: now,
  };

  const parent3: User = {
    id: 'parent-003', name: 'David Thompson', email: 'dthompson@email.com',
    role: 'parent', phone1: '0615551234', phone2: '0615551235',
    xafada: 'Dharkenley', udow: 'Ex-Control', 
    createdAt: now,
  };

  const users = [admin, teacher1, teacher2, parent1, parent2, parent3];

  // Students
  const students: Student[] = [
    { id: 'student-001', name: 'Emma Johnson', className: 'Grade 10-A', parentId: 'parent-001', createdAt: now },
    { id: 'student-002', name: 'Liam Johnson', className: 'Grade 8-B', parentId: 'parent-001', createdAt: now },
    { id: 'student-003', name: 'Sofia Rodriguez', className: 'Grade 10-A', parentId: 'parent-002', createdAt: now },
    { id: 'student-004', name: 'Noah Thompson', className: 'Grade 9-A', parentId: 'parent-003', createdAt: now },
    { id: 'student-005', name: 'Ava Thompson', className: 'Grade 7-C', parentId: 'parent-003', createdAt: now },
  ];

  // Comprehensive exam data for reports
  const subjects = ['Mathematics', 'English', 'Science', 'Somali', 'Islamic Studies'];
  const exams: Exam[] = [];
  let examCounter = 1;

  function addExam(
    studentId: string, subject: string, score: number, total: number,
    examType: ExamType, month: string, status: ExamStatus,
    parentId: string, teacherId: string, dateStr: string
  ) {
    exams.push({
      id: `exam-${String(examCounter++).padStart(3, '0')}`,
      studentId, subject, score, total, examType, month, status,
      parentId, date: dateStr, createdAt: now, teacherId,
    });
  }

  // ─── Student 1: Emma Johnson (Grade 10-A, parent-001) ───
  // January CA work
  subjects.forEach((sub, i) => {
    addExam('student-001', sub, [85, 78, 92, 88, 76][i], 100, 'CA', 'January', 'approved', 'parent-001', 'teacher-001', '2025-01-15');
    addExam('student-001', sub, [80, 82, 88, 85, 70][i], 100, 'Homework', 'January', 'approved', 'parent-001', 'teacher-001', '2025-01-20');
  });
  // February CA work
  subjects.forEach((sub, i) => {
    addExam('student-001', sub, [90, 85, 95, 82, 80][i], 100, 'CA', 'February', 'approved', 'parent-001', 'teacher-001', '2025-02-10');
    addExam('student-001', sub, [88, 80, 90, 86, 78][i], 100, 'Classwork', 'February', 'approved', 'parent-001', 'teacher-002', '2025-02-18');
    addExam('student-001', sub, [82, 76, 88, 84, 72][i], 100, 'Quiz', 'February', 'approved', 'parent-001', 'teacher-001', '2025-02-25');
  });
  // March - Midterm
  subjects.forEach((sub, i) => {
    addExam('student-001', sub, [88, 82, 94, 86, 78][i], 100, 'Midterm', 'March', 'approved', 'parent-001', 'teacher-001', '2025-03-15');
  });
  // April CA
  subjects.forEach((sub, i) => {
    addExam('student-001', sub, [92, 88, 96, 90, 82][i], 100, 'CA', 'April', 'approved', 'parent-001', 'teacher-001', '2025-04-10');
    addExam('student-001', sub, [86, 84, 90, 88, 80][i], 100, 'Homework', 'April', 'approved', 'parent-001', 'teacher-002', '2025-04-20');
  });
  // May - Final
  subjects.forEach((sub, i) => {
    addExam('student-001', sub, [90, 86, 95, 88, 80][i], 100, 'Final', 'May', 'approved', 'parent-001', 'teacher-001', '2025-05-20');
  });

  // ─── Student 2: Liam Johnson (Grade 8-B, parent-001) ───
  subjects.forEach((sub, i) => {
    addExam('student-002', sub, [72, 68, 80, 75, 65][i], 100, 'CA', 'January', 'approved', 'parent-001', 'teacher-001', '2025-01-15');
    addExam('student-002', sub, [70, 72, 78, 74, 60][i], 100, 'Homework', 'January', 'approved', 'parent-001', 'teacher-001', '2025-01-22');
  });
  subjects.forEach((sub, i) => {
    addExam('student-002', sub, [78, 74, 82, 80, 68][i], 100, 'CA', 'February', 'approved', 'parent-001', 'teacher-001', '2025-02-12');
    addExam('student-002', sub, [75, 70, 80, 76, 66][i], 100, 'Quiz', 'February', 'approved', 'parent-001', 'teacher-001', '2025-02-26');
  });
  subjects.forEach((sub, i) => {
    addExam('student-002', sub, [76, 72, 84, 78, 66][i], 100, 'Midterm', 'March', 'approved', 'parent-001', 'teacher-001', '2025-03-15');
  });
  subjects.forEach((sub, i) => {
    addExam('student-002', sub, [80, 76, 86, 82, 70][i], 100, 'CA', 'April', 'approved', 'parent-001', 'teacher-001', '2025-04-12');
  });
  subjects.forEach((sub, i) => {
    addExam('student-002', sub, [78, 74, 85, 80, 68][i], 100, 'Final', 'May', 'approved', 'parent-001', 'teacher-001', '2025-05-22');
  });

  // ─── Student 3: Sofia Rodriguez (Grade 10-A, parent-002) ───
  subjects.forEach((sub, i) => {
    addExam('student-003', sub, [95, 90, 88, 92, 86][i], 100, 'CA', 'January', 'approved', 'parent-002', 'teacher-001', '2025-01-15');
    addExam('student-003', sub, [92, 88, 85, 90, 84][i], 100, 'Homework', 'January', 'approved', 'parent-002', 'teacher-002', '2025-01-21');
  });
  subjects.forEach((sub, i) => {
    addExam('student-003', sub, [96, 92, 90, 94, 88][i], 100, 'CA', 'February', 'approved', 'parent-002', 'teacher-001', '2025-02-14');
    addExam('student-003', sub, [90, 86, 88, 92, 82][i], 100, 'Classwork', 'February', 'approved', 'parent-002', 'teacher-002', '2025-02-20');
  });
  subjects.forEach((sub, i) => {
    addExam('student-003', sub, [94, 90, 92, 96, 88][i], 100, 'Midterm', 'March', 'approved', 'parent-002', 'teacher-001', '2025-03-15');
  });
  subjects.forEach((sub, i) => {
    addExam('student-003', sub, [98, 94, 92, 96, 90][i], 100, 'CA', 'April', 'approved', 'parent-002', 'teacher-001', '2025-04-10');
  });
  subjects.forEach((sub, i) => {
    addExam('student-003', sub, [96, 92, 94, 98, 90][i], 100, 'Final', 'May', 'approved', 'parent-002', 'teacher-001', '2025-05-20');
  });

  // ─── Student 4: Noah Thompson (Grade 9-A, parent-003) ───
  subjects.forEach((sub, i) => {
    addExam('student-004', sub, [65, 70, 58, 72, 60][i], 100, 'CA', 'January', 'approved', 'parent-003', 'teacher-001', '2025-01-16');
    addExam('student-004', sub, [60, 68, 55, 70, 58][i], 100, 'Homework', 'January', 'approved', 'parent-003', 'teacher-001', '2025-01-23');
  });
  subjects.forEach((sub, i) => {
    addExam('student-004', sub, [70, 72, 62, 76, 64][i], 100, 'CA', 'February', 'approved', 'parent-003', 'teacher-001', '2025-02-11');
    addExam('student-004', sub, [68, 74, 60, 72, 62][i], 100, 'Quiz', 'February', 'approved', 'parent-003', 'teacher-001', '2025-02-24');
  });
  subjects.forEach((sub, i) => {
    addExam('student-004', sub, [72, 76, 64, 78, 66][i], 100, 'Midterm', 'March', 'approved', 'parent-003', 'teacher-001', '2025-03-16');
  });
  subjects.forEach((sub, i) => {
    addExam('student-004', sub, [74, 78, 66, 80, 68][i], 100, 'CA', 'April', 'pending', 'parent-003', 'teacher-001', '2025-04-14');
  });
  subjects.forEach((sub, i) => {
    addExam('student-004', sub, [70, 74, 62, 76, 64][i], 100, 'Final', 'May', 'pending', 'parent-003', 'teacher-001', '2025-05-21');
  });

  // ─── Student 5: Ava Thompson (Grade 7-C, parent-003) ───
  subjects.forEach((sub, i) => {
    addExam('student-005', sub, [88, 82, 90, 84, 78][i], 100, 'CA', 'January', 'approved', 'parent-003', 'teacher-002', '2025-01-17');
    addExam('student-005', sub, [85, 80, 88, 82, 76][i], 100, 'Classwork', 'January', 'approved', 'parent-003', 'teacher-002', '2025-01-24');
  });
  subjects.forEach((sub, i) => {
    addExam('student-005', sub, [90, 86, 92, 88, 82][i], 100, 'CA', 'February', 'approved', 'parent-003', 'teacher-002', '2025-02-13');
    addExam('student-005', sub, [86, 82, 90, 84, 78][i], 100, 'Quiz', 'February', 'approved', 'parent-003', 'teacher-002', '2025-02-27');
  });
  subjects.forEach((sub, i) => {
    addExam('student-005', sub, [88, 84, 92, 86, 80][i], 100, 'Midterm', 'March', 'approved', 'parent-003', 'teacher-002', '2025-03-17');
  });
  subjects.forEach((sub, i) => {
    addExam('student-005', sub, [92, 88, 94, 90, 84][i], 100, 'CA', 'April', 'approved', 'parent-003', 'teacher-002', '2025-04-11');
  });
  subjects.forEach((sub, i) => {
    addExam('student-005', sub, [90, 86, 94, 88, 82][i], 100, 'Final', 'May', 'approved', 'parent-003', 'teacher-002', '2025-05-22');
  });

  await bulkCreateUsers(users);
  await bulkCreateStudents(students);
  await bulkCreateExams(exams);
}

export async function clearDatabase(): Promise<void> {
  await supabase.from('exams').delete().neq('id', '');
  await supabase.from('students').delete().neq('id', '');
  await supabase.from('users').delete().neq('id', '');
}
