import { createClient } from '@supabase/supabase-js'

// These should be set in environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'your-supabase-url'
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-supabase-anon-key'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
// Generated by Copilot
// Test connection in non-production only and limit to a small probe
if (import.meta.env && import.meta.env.MODE !== 'production') {
  supabase.from('users').select('id', { count: 'estimated' }).limit(1).then(({ error }) => {
    if (error) {
      console.error('Supabase connection error:', error)
    } else {
      console.log('Supabase connected successfully')
    }
  })
}