import { AcademicYear, Term } from '../../types';
import { supabase } from '../supabase';

export async function getAcademicYears(): Promise<AcademicYear[]> {
  const { data, error } = await supabase
    .from('academic_years')
    .select('*')
    .order('startDate', { ascending: false });
  if (error) throw error;
  return (data || []) as AcademicYear[];
}

export async function createAcademicYear(payload: Omit<AcademicYear, 'id' | 'createdAt'>): Promise<AcademicYear> {
  const timestamp = Date.now();
  const rand = Math.random().toString(36).substring(2, 8);
  const id = `ay-${timestamp}-${rand}`;
  const insertPayload = { id, ...payload, createdAt: new Date().toISOString() } as any;
  const { data, error } = await supabase
    .from('academic_years')
    .insert(insertPayload)
    .select()
    .single();
  if (error) throw error;
  return data as AcademicYear;
}

export async function updateAcademicYear(id: string, payload: Partial<Omit<AcademicYear, 'id' | 'createdAt'>>): Promise<AcademicYear> {
  const { data, error } = await supabase
    .from('academic_years')
    .update(payload)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as AcademicYear;
}

export async function deleteAcademicYear(id: string): Promise<boolean> {
  // Delete associated terms first to avoid FK constraint errors
  const { error: termDeleteErr } = await supabase.from('terms').delete().eq('academicYearId', id);
  if (termDeleteErr) throw termDeleteErr;

  const { error } = await supabase
    .from('academic_years')
    .delete()
    .eq('id', id);
  if (error) throw error;
  return true;
}

export async function getTerms(): Promise<(Term & { academic_years?: AcademicYear })[]> {
  const { data, error } = await supabase
    .from('terms')
    .select('*, academic_years(*)')
    .order('startDate', { ascending: false });
  if (error) throw error;
  return (data || []) as (Term & { academic_years?: AcademicYear })[];
}

export async function createTerm(payload: Omit<Term, 'id' | 'createdAt'>): Promise<Term> {
  const timestamp = Date.now();
  const rand = Math.random().toString(36).substring(2, 8);
  const id = `term-${timestamp}-${rand}`;
  const insertPayload = { id, ...payload, createdAt: new Date().toISOString() } as any;
  const { data, error } = await supabase
    .from('terms')
    .insert(insertPayload)
    .select()
    .single();
  if (error) throw error;
  return data as Term;
}

export async function updateTerm(id: string, payload: Partial<Omit<Term, 'id' | 'createdAt'>>): Promise<Term> {
  const { data, error } = await supabase
    .from('terms')
    .update(payload)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as Term;
}

export async function deleteTerm(id: string): Promise<boolean> {
  const { error } = await supabase
    .from('terms')
    .delete()
    .eq('id', id);
  if (error) throw error;
  return true;
}

// Generated by Copilot
// (subject helpers moved to src/lib/db/subjects.ts)
