import { ReportComment } from '../../types';
import { supabase } from '../supabase';

export async function getReportComment(studentId: string, termId: string, examId?: string): Promise<ReportComment | null> {
  let query = supabase
    .from('report_comments')
    .select('*')
    .eq('studentId', studentId)
    .eq('termId', termId);

  if (examId) query = query.eq('examId', examId);

  const { data, error } = await query.maybeSingle();
  if (error) throw error;
  return (data as ReportComment) || null;
}

export async function upsertReportComment(payload: Partial<ReportComment> & { studentId: string; termId: string; examId?: string; teacherId?: string; teacherComment?: string }): Promise<ReportComment> {
  if (!payload.examId) throw new Error('examId is required for upserting a report comment');

  // Check existing
  const { data: existing, error: err1 } = await supabase
    .from('report_comments')
    .select('*')
    .eq('studentId', payload.studentId)
    .eq('termId', payload.termId)
    .eq('examId', payload.examId)
    .maybeSingle();
  if (err1) throw err1;

  if (existing) {
    const updatePayload = {
      teacherComment: payload.teacherComment ?? existing.teacherComment,
      principalComment: payload.principalComment ?? existing.principalComment,
      teacherId: payload.teacherId ?? existing.teacherId,
    };
    const { data: updated, error: err2 } = await supabase
      .from('report_comments')
      .update(updatePayload)
      .eq('id', (existing as any).id)
      .select()
      .single();
    if (err2) throw err2;
    return updated as ReportComment;
  }

  // Insert new
  const id = `rc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const insertPayload = {
    id,
    studentId: payload.studentId,
    termId: payload.termId,
    examId: payload.examId,
    teacherComment: payload.teacherComment ?? null,
    principalComment: payload.principalComment ?? null,
    teacherId: payload.teacherId ?? null,
  };

  const { data: inserted, error: err3 } = await supabase
    .from('report_comments')
    .insert(insertPayload)
    .select()
    .single();
  if (err3) throw err3;
  return inserted as ReportComment;
}

export async function getReportCommentsForStudentTerm(studentId: string, termId: string): Promise<Pick<ReportComment, 'id' | 'teacherId' | 'teacherComment' | 'principalComment' | 'examId' | 'createdAt'>[]> {
  const { data, error } = await supabase
    .from('report_comments')
    .select('id, studentId, termId, teacherId, teacherComment, principalComment, examId, createdAt')
    .eq('studentId', studentId)
    .eq('termId', termId)
    .order('createdAt', { ascending: true });
  if (error) throw error;
  return (data || []) as Pick<ReportComment, 'id' | 'studentId' | 'termId' | 'teacherId' | 'teacherComment' | 'principalComment' | 'examId' | 'createdAt'>[];
}

// Generated by Copilot
