import { Exam, FinalReport, GradeScale, MidtermReport, MidtermScore, MonthlyScore, ReportComment, ReportConfig, getGrade } from '../../types';
import { getStudentById } from './students';
import { supabase } from '../supabase';
import { warnFallback } from '../logger';

export async function getReportComment(studentId: string, termId: string, examId?: string): Promise<ReportComment | null> {
  let query = supabase
    .from('report_comments')
    .select('*')
    .eq('studentId', studentId)
    .eq('termId', termId);

  if (examId) query = query.eq('examId', examId);

  const { data, error } = await query.maybeSingle();
  if (error) throw error;
  return (data as ReportComment) || null;
}

export async function upsertReportComment(payload: Partial<ReportComment> & { studentId: string; termId: string; examId?: string; teacherId?: string; teacherComment?: string }): Promise<ReportComment> {
  if (!payload.examId) throw new Error('examId is required for upserting a report comment');

  // Check existing
  const { data: existing, error: err1 } = await supabase
    .from('report_comments')
    .select('*')
    .eq('studentId', payload.studentId)
    .eq('termId', payload.termId)
    .eq('examId', payload.examId)
    .maybeSingle();
  if (err1) throw err1;

  if (existing) {
    const updatePayload = {
      teacherComment: payload.teacherComment ?? existing.teacherComment,
      principalComment: payload.principalComment ?? existing.principalComment,
      teacherId: payload.teacherId ?? existing.teacherId,
    };
    const { data: updated, error: err2 } = await supabase
      .from('report_comments')
      .update(updatePayload)
      .eq('id', (existing as any).id)
      .select()
      .single();
    if (err2) throw err2;
    return updated as ReportComment;
  }

  // Insert new
  const id = `rc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const insertPayload = {
    id,
    studentId: payload.studentId,
    termId: payload.termId,
    examId: payload.examId,
    teacherComment: payload.teacherComment ?? null,
    principalComment: payload.principalComment ?? null,
    teacherId: payload.teacherId ?? null,
  };

  const { data: inserted, error: err3 } = await supabase
    .from('report_comments')
    .insert(insertPayload)
    .select()
    .single();
  if (err3) throw err3;
  return inserted as ReportComment;
}

export async function getReportCommentsForStudentTerm(studentId: string, termId: string): Promise<Pick<ReportComment, 'id' | 'teacherId' | 'teacherComment' | 'principalComment' | 'examId' | 'createdAt'>[]> {
  const { data, error } = await supabase
    .from('report_comments')
    .select('id, studentId, termId, teacherId, teacherComment, principalComment, examId, createdAt')
    .eq('studentId', studentId)
    .eq('termId', termId)
    .order('createdAt', { ascending: true });
  if (error) throw error;
  return (data || []) as Pick<ReportComment, 'id' | 'studentId' | 'termId' | 'teacherId' | 'teacherComment' | 'principalComment' | 'examId' | 'createdAt'>[];
}

// Generated by Copilot

export async function getGradeScales(): Promise<GradeScale[]> {
  const { data, error } = await supabase.from('grade_scales').select('*');
  if (error) throw error;
  return data || [];
}

export async function getReportConfig(): Promise<ReportConfig> {
  const { data, error } = await supabase
    .from('report_config')
    .select('*')
    .eq('id', 'default')
    .single();
  if (error) throw error;
  return data;
}

// RPC functions for reports
export async function getMonthlyReport(
  studentId: string,
  termId: string
): Promise<MonthlyScore[]> {
  const { data, error } = await supabase.rpc('get_monthly_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });
  if (error) throw error;
  return data;
}

export async function getMidtermReport(
  studentId: string,
  termId: string
): Promise<MidtermReport> {
  const { data, error } = await supabase.rpc('get_midterm_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });

  if (!error) return data;

  const isMissingRpc = error.code === 'PGRST202'
    || (error as any).status === 404
    || (typeof error.message === 'string' && error.message.includes('Not Found'))
    || (typeof error.details === 'string' && error.details.includes('get_midterm_report'));

  if (isMissingRpc) {
    warnFallback('get_midterm_report RPC missing; using client fallback', error);
    return getMidtermReportFallback(studentId, termId);
  }

  throw error;
}

export async function getMidtermReportFallback(studentId: string, termId: string): Promise<MidtermReport> {
  const student = await getStudentById(studentId);
  if (!student) {
    return { scores: [], overall_rank: 0, total_students: 0 };
  }

  const [studentExamsResult, classStudentsResult] = await Promise.all([
    supabase
      .from('exams')
      .select('id, studentId, subject, score, total')
      .eq('studentId', studentId)
      .eq('termId', termId)
      .eq('examType', 'Midterm')
      .eq('status', 'approved')
      .returns<Exam[]>(),
    supabase
      .from('students')
      .select('id')
      .eq('className', student.className)
      .returns<{ id: string }[]>(),
  ]);

  const { data: studentExams, error: studentError } = studentExamsResult;
  const { data: classStudents, error: classError } = classStudentsResult;

  if (studentError) throw studentError;
  if (classError) throw classError;

  const classStudentIds = classStudents?.map(s => s.id) ?? [];

  const { data: classExams, error: classExamsError } = classStudentIds.length > 0
    ? await supabase
        .from('exams')
        .select('id, studentId, subject, score, total')
        .in('studentId', classStudentIds)
        .eq('termId', termId)
        .eq('examType', 'Midterm')
        .eq('status', 'approved')
        .returns<Exam[]>()
    : { data: [], error: null };

  if (classExamsError) throw classExamsError;

  const bySubject = new Map<string, MidtermScore>();

  for (const e of studentExams ?? []) {
    const percentage = e.total > 0 ? Math.round((e.score / e.total) * 100) : 0;
    const grade = getGrade(percentage);
    const remark = grade === 'A' ? 'Excellent' : grade === 'B' ? 'Very Good' : grade === 'C' ? 'Good' : grade === 'D' ? 'Satisfactory' : 'Needs Improvement';

    const sameSubjectClass = (classExams ?? []).filter(ex => ex.subject === e.subject);
    const classAvg = sameSubjectClass.length
      ? Math.round(sameSubjectClass.reduce((sum, ex) => sum + (ex.total > 0 ? (ex.score / ex.total) * 100 : 0), 0) / sameSubjectClass.length)
      : 0;

    const highestInClass = sameSubjectClass.length
      ? Math.max(...sameSubjectClass.map(ex => (ex.total > 0 ? Math.round((ex.score / ex.total) * 100) : 0)))
      : 0;

    const sortedSubject = [...sameSubjectClass]
      .map(ex => (ex.total > 0 ? Math.round((ex.score / ex.total) * 100) : 0))
      .sort((a, b) => b - a);

    const subjectRank = sortedSubject.indexOf(percentage) + 1;

    bySubject.set(e.subject, {
      subject: e.subject,
      score: e.score,
      total: e.total,
      percentage,
      grade,
      remark,
      subject_rank: subjectRank || 1,
      class_average: classAvg,
      highest_in_class: highestInClass,
      examId: e.id,
    });
  }

  const scores = Array.from(bySubject.values());

  const studentAverage = scores.length
    ? Math.round(scores.reduce((sum, s) => sum + s.percentage, 0) / scores.length)
    : 0;

  const classAverages = new Map<string, number>();
  for (const sid of classStudentIds) {
    const exams = (classExams ?? []).filter(ex => ex.studentId === sid);
    const pct = exams.length
      ? Math.round(exams.reduce((sum, ex) => sum + (ex.total > 0 ? (ex.score / ex.total) * 100 : 0), 0) / exams.length)
      : 0;
    classAverages.set(sid, pct);
  }

  const sortedClassAverages = [...classAverages.values()].sort((a, b) => b - a);
  const overall_rank = sortedClassAverages.indexOf(studentAverage) + 1;
  const total_students = classAverages.size;

  return { scores, overall_rank: overall_rank || 0, total_students };
}

export async function getFinalReport(
  studentId: string,
  termId: string
): Promise<FinalReport> {
  const { data, error } = await supabase.rpc('get_final_report', {
    p_student_id: studentId,
    p_term_id: termId,
  });
  if (error) throw error;
  return data;
}
