// Generated by Copilot

import { Student } from '../../types';
import { supabase } from '../supabase';

const MAX_QUERY_LIMIT = 500000;

// debug intentionally removed to avoid unused warnings

function applyLimit(query: any, limit: number) {
  if (typeof query.limit === 'function') {
    return query.limit(Math.min(limit, MAX_QUERY_LIMIT));
  }
  return query;
}

export async function getStudents(limit: number = MAX_QUERY_LIMIT): Promise<Student[]> {
  const { data, error } = await applyLimit(
    supabase.from('students').select('id,name,className,parentId,createdAt'),
    limit
  );
  if (error) throw error;
  return (data || []) as Student[];
}

export async function getStudentsPaginated(page: number = 1, limit: number = 50, search?: string): Promise<{ students: Student[]; total: number }> {
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase
    .from('students')
    .select('*', { count: 'exact' });

  if (search && search.trim()) {
    query = query.ilike('name', `%${search}%`);
  }

  const { data, error, count } = await query.range(from, to);
  if (error) throw error;
  return { students: (data || []) as Student[], total: count || 0 };
}

export async function getStudentById(id: string): Promise<Student | undefined> {
  const { data, error } = await supabase
    .from('students')
    .select('id,name,className,parentId,createdAt')
    .eq('id', id)
    .single();
  if (error) return undefined;
  return data as Student | undefined;
}

export async function getStudentsByParent(parentId: string): Promise<Student[]> {
  const { data, error } = await supabase
    .from('students')
    .select('id,name,className,parentId,createdAt')
    .eq('parentId', parentId);
  if (error) throw error;
  return (data || []) as Student[];
}

export async function getStudentsByClass(className: string, limit: number = 100): Promise<Student[]> {
  const { data, error } = await applyLimit(
    supabase.from('students').select('id,name,className,parentId,createdAt').eq('className', className),
    limit
  );
  if (error) throw error;
  return (data || []) as Student[];
}

export async function getStudentsByIds(ids: string[], limit: number = MAX_QUERY_LIMIT): Promise<Student[]> {
  if (!Array.isArray(ids) || ids.length === 0) return [];
  const { data, error } = await applyLimit(
    supabase.from('students').select('id,name,className,parentId,createdAt').in('id', ids),
    limit
  );
  if (error) throw error;
  return (data || []) as Student[];
}

export async function getStudentsByClasses(classnames: string[], search?: string, limit: number = MAX_QUERY_LIMIT): Promise<Student[]> {
  let query = applyLimit(
    supabase.from('students').select('id,name,className,parentId,createdAt'),
    limit
  );
  if (classnames && classnames.length > 0) {
    query = query.in('className', classnames);
  }
  if (search && search.trim()) {
    query = query.ilike('name', `%${search}%`);
  }
  const { data, error } = await query;
  if (error) throw error;
  return (data || []) as Student[];
}

export async function getStudentClasses(): Promise<string[]> {
  const { data, error } = await supabase.from('students').select('className');
  if (error) throw error;
  const rows = (data || []) as Array<{ className?: string }>;
  const classes = Array.from(new Set(rows.map(r => r.className).filter(Boolean)));
  classes.sort();
  return classes as string[];
}

export async function createStudent(data: Omit<Student, 'id' | 'createdAt'>): Promise<Student> {
  const timestamp = Date.now();
  const rand = Math.random().toString(36).substring(2, 8);
  const id = `student-${timestamp}-${rand}`;

  const payload = { id, ...data, createdAt: new Date().toISOString() } as any;
  const { data: created, error } = await supabase.from('students').insert(payload).select().single();
  if (error) {
    console.error('Error creating student:', error);
    throw error;
  }
  return created as Student;
}

export async function updateStudent(id: string, data: Partial<Student>): Promise<Student | null> {
  const { data: updated, error } = await supabase.from('students').update(data).eq('id', id).select().single();
  if (error) {
    console.error('Error updating student:', error);
    return null;
  }
  return updated as Student;
}

export async function deleteStudent(id: string): Promise<boolean> {
  const { error } = await supabase.from('students').delete().eq('id', id);
  if (error) {
    console.error('Error deleting student:', error);
    return false;
  }
  await supabase.from('exams').delete().eq('studentId', id);
  return true;
}

export async function promoteStudentsByClass(fromClass: string, toClass: string): Promise<number> {
  const { data: rows, error: readError } = await supabase
    .from('students')
    .select('id')
    .eq('className', fromClass);
  if (readError) throw readError;

  const ids = (rows || []).map((row: { id: string }) => row.id);
  if (ids.length === 0) return 0;

  const { error: updateError } = await supabase
    .from('students')
    .update({ className: toClass })
    .in('id', ids);
  if (updateError) throw updateError;

  return ids.length;
}
