import { Subject } from '../../types';
import { supabase } from '../supabase';

export async function getSubjects(): Promise<Subject[]> {
  const { data, error } = await supabase.from('subjects').select('*');
  if (error) throw error;
  return (data || []) as Subject[];
}

export async function createSubject(payload: Omit<Subject, 'id' | 'createdAt'>): Promise<Subject> {
  const timestamp = Date.now();
  const rand = Math.random().toString(36).substring(2, 8);
  const id = `subject-${timestamp}-${rand}`;
  const insertPayload = { id, ...payload, createdAt: new Date().toISOString() } as any;
  const { data, error } = await supabase.from('subjects').insert(insertPayload).select().single();
  if (error) throw error;
  return data as Subject;
}

export async function updateSubject(id: string, payload: Partial<Omit<Subject, 'id' | 'createdAt'>>): Promise<Subject> {
  const { data, error } = await supabase.from('subjects').update(payload).eq('id', id).select().single();
  if (error) throw error;
  return data as Subject;
}

export async function deleteSubject(id: string): Promise<boolean> {
  // Remove any class_subjects mappings that reference this subject to avoid FK constraint errors
  const { error: csError } = await supabase.from('class_subjects').delete().eq('subjectId', id);
  if (csError) throw csError;

  const { error } = await supabase.from('subjects').delete().eq('id', id);
  if (error) throw error;
  return true;
}

// Generated by Copilot
