// Generated by Copilot
import React, { useEffect, useState } from 'react';
import { useTeacherExamProgress } from '@/lib/hooks';
import type { TeacherExamProgress } from '../../types';

type MaybeNumber = number | null;

const SUBJECTS = [
  'Arabic', 'Biology', 'Chemistry', 'English', 'History', 'Islamic Studies', 'Mathematics', 'Physics', 'Science'
];


// (legacy mock data removed)

function getColorForPercent(p: MaybeNumber) {
  if (p === null || p === undefined) return { bg: 'bg-slate-100', text: 'text-slate-400' };
  if (p === 100) return { bg: 'bg-emerald-600', text: 'text-white' };
  if (p >= 75) return { bg: 'bg-emerald-400', text: 'text-white' };
  if (p >= 50) return { bg: 'bg-amber-300', text: 'text-slate-800' };
  if (p >= 25) return { bg: 'bg-orange-300', text: 'text-slate-800' };
  if (p >= 1) return { bg: 'bg-rose-200', text: 'text-slate-800' };
  return { bg: 'bg-rose-600', text: 'text-white' };
}

const HeatMap: React.FC<{ month?: string; classNames?: string[] }> = ({ month, classNames }) => {
  const [subjects, setSubjects] = useState<string[]>(SUBJECTS);
  const [stats, setStats] = useState<Array<{
    teacher: string;
    values: MaybeNumber[];
    avg: MaybeNumber;
    details?: Record<string, TeacherExamProgress[]>;
    classCount: number;
    subjectCount: number;
  }>>([]);
  const { data: rows = [], isLoading } = useTeacherExamProgress({ month, classNames });
  const [loading, setLoading] = useState(false);
  const [modal, setModal] = useState<{
    open: boolean;
    teacher?: string;
    subject?: string;
    details?: TeacherExamProgress[];
  }>({ open: false });

  useEffect(() => {
    const subjectList = Array.from(new Set(rows.map((r) => r.subjectName || r.subjectId))).sort();
    const currentSubjects = subjectList.length > 0 ? subjectList : SUBJECTS;
    setSubjects(currentSubjects);

    const teacherList = Array.from(new Set(rows.map(r => r.teacherName))).filter(Boolean) as string[];
    const teacherRows = new Map<string, TeacherExamProgress[]>();
    rows.forEach((row) => {
      const teacher = row.teacherName;
      if (!teacherRows.has(teacher)) teacherRows.set(teacher, []);
      teacherRows.get(teacher)!.push(row);
    });

    const matrix = teacherList.map(t => {
      const teacherData = teacherRows.get(t) || [];
      const rowDetails: Record<string, TeacherExamProgress[]> = {};
      const values = currentSubjects.map(s => {
        const matching = teacherData.filter(rr => rr.subjectName === s || rr.subjectId === s);
        if (matching.length > 0) {
          rowDetails[s] = matching;
          return Math.round(matching.reduce((sum, rr) => sum + rr.completionPercent, 0) / matching.length);
        }
        return null;
      });
      const nums = values.filter(v => v !== null) as number[];
      const avg = nums.length === 0 ? null : Math.round(nums.reduce((a, b) => a + b, 0) / nums.length);
      const classCount = new Set(teacherData.map(rr => rr.className)).size;
      const subjectCount = teacherData.length > 0 ? new Set(teacherData.map(rr => rr.subjectName || rr.subjectId)).size : 0;
      return { teacher: t, values, avg, details: rowDetails, classCount, subjectCount };
    });

    setStats(matrix);
    setLoading(isLoading);
  }, [rows, isLoading]);

  const gridColumns = `220px repeat(${subjects.length}, minmax(0, 1fr)) 120px`;

  function openDetail(teacher: string, subject: string) {
    const entry = stats.find(s => s.teacher === teacher)?.details?.[subject] || [];
    setModal({ open: true, teacher, subject, details: entry });
  }

  const modalClasses = modal.details
    ? Array.from(new Map(modal.details.map((detail) => [detail.className, detail])).values())
    : [];

  return (
    <div className="p-6 max-w-full">
      <div className="rounded-xl bg-white shadow-sm p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h3 className="text-xl font-semibold">Completion Heat Map</h3>
            <p className="text-sm text-slate-500">Each cell shows completion % per teacher × subject combination</p>
          </div>
          <div className="flex items-center gap-4">
            <nav className="flex gap-2 bg-slate-50 rounded-md p-1">
              <button className="px-3 py-1 rounded-md text-slate-600">Progress Table</button>
              <button className="px-3 py-1 rounded-md bg-white text-indigo-600 font-medium">🔥 Heat Map</button>
              <button className="px-3 py-1 rounded-md text-slate-600">Notify Teachers <span className="ml-1 inline-block bg-pink-500 text-white text-xs px-2 py-0.5 rounded-full">9</span></button>
              <button className="px-3 py-1 rounded-md text-slate-600">SQL / API Ref</button>
            </nav>
          </div>
        </div>

        <div className="overflow-x-auto">
          <div className="min-w-[980px]">
            <div className="grid gap-2 items-center" style={{ gridTemplateColumns: gridColumns }}>
              <div className="px-4 py-3 text-xs font-semibold text-slate-600">TEACHER ↓ / SUBJECT →</div>
              {subjects.map((s) => (
                <div key={s} className="px-4 py-3 text-xs font-semibold text-slate-600 text-center">{s}</div>
              ))}
              <div className="px-4 py-3 text-xs font-semibold text-slate-600 text-center">Avg</div>

              {loading ? (
                <div className="col-span-full py-16 text-center text-slate-500">Loading heat map…</div>
              ) : stats.length === 0 ? (
                <div className="col-span-full py-16 text-center text-slate-500">No data to display for the selected month.</div>
              ) : (
                stats.map((row) => (
                  <React.Fragment key={row.teacher}>
                    <div className="flex flex-col gap-1 px-4 py-3">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-full bg-indigo-100 flex items-center justify-center font-semibold text-indigo-700">{row.teacher.split(' ').map(n=>n[0]).slice(0,2).join('')}</div>
                        <div>
                          <div className="text-sm font-medium">{row.teacher}</div>
                          <div className="text-xs text-slate-500">{row.classCount} class{row.classCount === 1 ? '' : 'es'} · {row.subjectCount} subj{row.subjectCount === 1 ? 'ect' : 'ects'}</div>
                        </div>
                      </div>
                    </div>

                    {row.values.map((v, i) => {
                      const subj = subjects[i];
                      const c = getColorForPercent(v);
                      const detailRows = row.details?.[subj] || [];
                      return (
                        <div key={i} className="p-4 flex items-center justify-center">
                          <div className="relative group">
                            <button
                              onClick={() => openDetail(row.teacher, subj)}
                              className={`w-20 h-10 rounded-md flex items-center justify-center transition-colors duration-300 ${c.bg} ${c.text}`}
                              type="button"
                            >
                              {v === null ? <span className="text-slate-400">—</span> : <span className="font-semibold">{v}%</span>}
                            </button>

                            <div className="pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-150 absolute -top-20 left-1/2 transform -translate-x-1/2 z-10 w-48">
                              <div className="bg-white border rounded shadow px-3 py-2 text-xs text-slate-700">
                                <div className="font-semibold mb-1">{v === null ? 'No entry' : `${v}% avg`}</div>
                                {detailRows.length > 0 ? (
                                  <div className="space-y-0.5">
                                    <div>{detailRows.length} class{detailRows.length === 1 ? '' : 'es'}</div>
                                    <div>CA: {detailRows.reduce((sum, detail) => sum + detail.caEntered, 0)}</div>
                                    <div>Quiz: {detailRows.reduce((sum, detail) => sum + detail.quizEntered, 0)}</div>
                                  </div>
                                ) : (
                                  <div className="text-slate-500">Click for class details</div>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })}

                    <div className="p-4 flex items-center justify-center">
                      <div className={`px-3 py-1 rounded-full border font-semibold ${getColorForPercent(row.avg).bg} ${getColorForPercent(row.avg).text}`}>{row.avg === null ? '—' : `${row.avg}%`}</div>
                    </div>
                  </React.Fragment>
                ))
              )}
            </div>
          </div>
        </div>

        <div className="mt-6 flex items-center gap-4 text-sm text-slate-600">
          <div className="font-semibold mr-2">LEGEND:</div>
          <LegendItem label="100%" bg="bg-emerald-600 text-white" />
          <LegendItem label="75–99%" bg="bg-emerald-400 text-white" />
          <LegendItem label="50–74%" bg="bg-amber-300 text-slate-800" />
          <LegendItem label="25–49%" bg="bg-orange-300 text-slate-800" />
          <LegendItem label="1–24%" bg="bg-rose-200 text-slate-800" />
          <LegendItem label="0%" bg="bg-rose-600 text-white" />
          <LegendItem label="N/A" bg="bg-slate-100 text-slate-400" />
        </div>

        {modal.open && (
          <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50 px-4">
            <div className="bg-white rounded-lg p-6 w-full max-w-2xl">
              <div className="flex justify-between items-center mb-4">
                <div>
                  <div className="text-lg font-semibold">{modal.teacher} — {modal.subject}</div>
                  <div className="text-xs text-slate-500">Detailed completion by class</div>
                </div>
                <button onClick={() => setModal({ open: false })} className="text-slate-500">Close</button>
              </div>
              {modal.details && modal.details.length > 0 ? (
                <div className="space-y-4 text-sm">
                  <div className="mb-3 rounded-lg bg-slate-50 p-4">
                    <div className="text-xs uppercase tracking-wide text-slate-500">Subject</div>
                    <div className="text-2xl font-semibold">{modal.subject}</div>
                    <div className="text-xs text-slate-500 mt-1">
                      {modalClasses.length} class{modalClasses.length === 1 ? '' : 'es'} • Avg {Math.round(modalClasses.reduce((sum, detail) => sum + detail.completionPercent, 0) / modalClasses.length)}%
                    </div>
                  </div>
                  <div className="grid gap-4">
                    {modalClasses.slice(0, 1).map((detail) => (
                      <div key={detail.className} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                        <div className="text-xs uppercase tracking-wide text-slate-500">Top class</div>
                        <div className="mt-2 text-lg font-semibold text-slate-900">{detail.className}</div>
                        <div className="mt-4 flex items-end gap-3">
                          <div className="text-4xl font-bold text-slate-900">{detail.completionPercent}%</div>
                          <div className="text-xs text-slate-500">{detail.completedEntries}/{detail.requiredEntries} entered</div>
                        </div>
                        <div className="mt-4 text-xs text-slate-600">{detail.missingExamTypes?.length ? `Missing: ${(detail.missingExamTypes || []).join(', ')}` : 'All entries complete'}</div>
                      </div>
                    ))}
                  </div>
                  {modalClasses.length > 1 && (
                    <div>
                      <div className="mb-3 text-sm font-semibold text-slate-900">Other classes</div>
                      <div className="grid gap-4 sm:grid-cols-2">
                        {modalClasses.slice(1).map((detail) => (
                          <div key={detail.className} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
                            <div className="text-sm font-semibold text-slate-900 mb-2">{detail.className}</div>
                            <div className="h-2 w-full overflow-hidden rounded-full bg-slate-200 mb-2">
                              <div className={`h-full rounded-full ${detail.completionPercent === 100 ? 'bg-emerald-500' : 'bg-amber-500'}`} style={{ width: `${detail.completionPercent}%` }} />
                            </div>
                            <div className="text-sm font-semibold">{detail.completionPercent}%</div>
                            <div className="mt-2 text-xs text-slate-600">{detail.missingExamTypes?.length ? `Missing: ${(detail.missingExamTypes || []).join(', ')}` : 'All entries complete'}</div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="text-sm text-slate-500">No detailed records found for this selection.</div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

const LegendItem: React.FC<{ label: string; bg: string }> = ({ label, bg }) => (
  <div className="flex items-center gap-2">
    <div className={`w-8 h-6 rounded-md flex items-center justify-center ${bg} shadow-sm`}></div>
    <div className="text-xs">{label}</div>
  </div>
);

export default HeatMap;
