// Generated by Copilot
import { useEffect, useMemo, useState } from 'react';
import { useRole } from '../../context/RoleContext';
import { getTeacherExamProgress, getSupervisorDashboardData } from '@/lib/db';
import { MONTHS, TeacherExamProgress } from '../../types';
import HeatMap from '../../components/HeatMap/HeatMap';

const getCardTintClasses = (percent: number) => {
  if (percent <= 30) return 'bg-rose-50/90 border-rose-200 text-rose-900';
  if (percent <= 70) return 'bg-amber-50/90 border-amber-200 text-amber-900';
  return 'bg-emerald-50/90 border-emerald-200 text-emerald-900';
};

const getStatusBadgeClasses = (status: 'complete' | 'incomplete') =>
  status === 'complete' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800';

const getRequiredEntryInfo = (detail: TeacherExamProgress) => {
  const quizDone = detail.quizEntered > 0;
  const caDone = detail.caEntered > 0;
  const homeworkDone = detail.homeworkEntered > 0;
  const classworkDone = detail.classworkEntered > 0;
  const attendanceDone = detail.attendanceEntered > 0;

  const requiredItems = caDone
    ? ['Quiz', 'CA']
    : ['Quiz', 'Homework', 'Classwork', 'Attendance'];

  const completedRequiredItems = [
    quizDone ? 'Quiz' : null,
    caDone ? 'CA' : null,
    !caDone && homeworkDone ? 'Homework' : null,
    !caDone && classworkDone ? 'Classwork' : null,
    !caDone && attendanceDone ? 'Attendance' : null,
  ].filter(Boolean) as string[];

  const allCompletedItems = [
    quizDone ? 'Quiz' : null,
    caDone ? 'CA' : null,
    homeworkDone ? 'Homework' : null,
    classworkDone ? 'Classwork' : null,
    attendanceDone ? 'Attendance' : null,
  ].filter(Boolean) as string[];

  const isComplete = completedRequiredItems.length === requiredItems.length;
  const displayPercent = Math.round((completedRequiredItems.length / requiredItems.length) * 100);

  return {
    requiredItems,
    completedRequiredItems,
    completedItems: allCompletedItems,
    requiredCount: requiredItems.length,
    completedCount: completedRequiredItems.length,
    displayPercent,
    isComplete,
    quizDone,
    caDone,
    homeworkDone,
    classworkDone,
    attendanceDone,
  };
};

export function SupervisorDashboard() {
  const { session } = useRole();
  const [progressRows, setProgressRows] = useState<TeacherExamProgress[]>([]);
  const [classes, setClasses] = useState<string[]>([]);
  const [supervisorClasses, setSupervisorClasses] = useState<string[]>([]);
  const [monthOptions, setMonthOptions] = useState<string[]>([]);
  const [selectedMonth, setSelectedMonth] = useState<string>('');
  const [selectedClass, setSelectedClass] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [initialMonthLoaded, setInitialMonthLoaded] = useState(false);
  const [activeTab, setActiveTab] = useState<'table' | 'heat' | 'notify' | 'sql'>('table');
  const [selectedDetail, setSelectedDetail] = useState<TeacherExamProgress | null>(null);

  useEffect(() => {
    async function loadSupervisorClasses() {
      if (!session || session.role !== 'supervisor') return;
      setLoading(true);
      setError(null);
      try {
        const { assignedClasses } = await getSupervisorDashboardData(session.userId);
        setSupervisorClasses(assignedClasses);
        setClasses(assignedClasses);
        setSelectedClass('');
      } catch (err) {
        console.error(err);
        setError('Unable to load supervisor profile.');
      } finally {
        setLoading(false);
      }
    }
    loadSupervisorClasses();
  }, [session]);

  function notifyTeacher(teacherId: string) {
    // placeholder: integrate with email or messaging API
    console.log('Notify teacher', teacherId);
  }

  function notifyAllTeachers(rows: TeacherExamProgress[]) {
    const teacherIds = Array.from(new Set(rows.filter(r => r.completionStatus !== 'complete').map(r => r.teacherId)));
    console.log('Notify all teachers', teacherIds);
  }

  useEffect(() => {
    async function loadInitialProgress() {
      if (!session || session.role !== 'supervisor' || supervisorClasses.length === 0 || initialMonthLoaded) return;
      setLoading(true);
      setError(null);
      try {
        const rows = await getTeacherExamProgress({ classNames: supervisorClasses });
        const months = Array.from(new Set(rows.map(row => row.month))).sort((a, b) => MONTHS.indexOf(a) - MONTHS.indexOf(b));
        setMonthOptions(months);
        if (months.length > 0) {
          setSelectedMonth(months[0]);
          setProgressRows(rows.filter(row => row.month === months[0]));
        } else {
          setProgressRows([]);
        }
      } catch (err) {
        console.error(err);
        setError('Unable to load progress data.');
      } finally {
        setLoading(false);
        setInitialMonthLoaded(true);
      }
    }
    loadInitialProgress();
  }, [session, supervisorClasses, initialMonthLoaded]);

  useEffect(() => {
    async function loadProgress() {
      if (!session || session.role !== 'supervisor' || supervisorClasses.length === 0 || !initialMonthLoaded) return;
      if (!selectedMonth) return;
      setLoading(true);
      setError(null);
      try {
        const rows = await getTeacherExamProgress({ month: selectedMonth, classNames: selectedClass ? [selectedClass] : supervisorClasses });
        setProgressRows(rows);
      } catch (err) {
        console.error(err);
        setError('Unable to load progress data.');
      } finally {
        setLoading(false);
      }
    }
    loadProgress();
  }, [session, supervisorClasses, selectedClass, selectedMonth, initialMonthLoaded]);

  const displayMonthOptions = monthOptions.length > 0 ? monthOptions : MONTHS;

  const kpis = useMemo(() => {
    const totalRecords = progressRows.length;
    const complete = progressRows.filter(r => r.completionStatus === 'complete').length;
    const incomplete = totalRecords - complete;
    const totalTeachers = new Set(progressRows.map(r => r.teacherId)).size;
    const missingEntries = progressRows.reduce((acc, r) => acc + (r.missingExamTypes?.length || 0), 0);
    return { totalRecords, complete, incomplete, totalTeachers, missingEntries };
  }, [progressRows]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Supervisor Dashboard</h1>
        <p className="text-slate-500 mt-1">Monitor teacher monthly exam entry completion.</p>
      </div>

      <div className="flex flex-col gap-4 lg:flex-row lg:items-center">
        <div className="flex flex-wrap gap-2 bg-white rounded-lg p-1 shadow-sm">
          <button onClick={() => setActiveTab('table')} className={`px-3 py-2 rounded ${activeTab === 'table' ? 'bg-slate-100' : ''}`}>Progress Table</button>
          <button onClick={() => setActiveTab('heat')} className={`px-3 py-2 rounded ${activeTab === 'heat' ? 'bg-slate-100' : ''}`}>Heat Map</button>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap items-start">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 bg-white rounded-lg p-3 shadow-sm text-sm w-full sm:w-auto">
            <label htmlFor="month-select" className="font-medium text-slate-600">Month</label>
            <select
              id="month-select"
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="min-w-[160px] rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"
            >
              {displayMonthOptions.map((month) => (
                <option key={month} value={month}>{month}</option>
              ))}
            </select>
          </div>
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 bg-white rounded-lg p-3 shadow-sm text-sm w-full sm:w-auto">
            <label htmlFor="class-select" className="font-medium text-slate-600">Class</label>
            <select
              id="class-select"
              value={selectedClass}
              onChange={(e) => setSelectedClass(e.target.value)}
              className="min-w-[160px] rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"
            >
              <option value="">All classes</option>
              {supervisorClasses.map((cls) => (
                <option key={cls} value={cls}>{cls}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="ml-auto flex flex-wrap gap-3">
          <div className="bg-white rounded-lg p-3 shadow text-center w-full sm:w-40">
            <div className="text-sm text-slate-500">Teachers</div>
            <div className="text-xl font-semibold">{kpis.totalTeachers}</div>
          </div>
          <div className="bg-white rounded-lg p-3 shadow text-center w-full sm:w-40">
            <div className="text-sm text-slate-500">Records</div>
            <div className="text-xl font-semibold">{kpis.totalRecords}</div>
          </div>
          <div className="bg-white rounded-lg p-3 shadow text-center w-full sm:w-40">
            <div className="text-sm text-slate-500">Complete</div>
            <div className="text-xl font-semibold">{kpis.complete}</div>
          </div>
          <div className="bg-white rounded-lg p-3 shadow text-center w-full sm:w-40">
            <div className="text-sm text-slate-500">Incomplete</div>
            <div className="text-xl font-semibold">{kpis.incomplete}</div>
          </div>
        </div>
      </div>

      <div className="text-sm text-slate-600">Showing {progressRows.length} records</div>

      <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
        {activeTab === 'table' && (
          <>
            <div className="flex items-center justify-between gap-4 pb-4 border-b border-slate-200 mb-4">
              <div>
                <h2 className="text-lg font-semibold text-slate-900">Teacher Exam Progress</h2>
                <p className="text-sm text-slate-500">Showing progress for {selectedMonth || 'all entered months'}.</p>
              </div>
              <div className="text-sm text-slate-500">{progressRows.length} records</div>
            </div>
            {loading ? (
              <p className="text-sm text-slate-500">Loading progress...</p>
            ) : error ? (
              <p className="text-sm text-rose-600">{error}</p>
            ) : progressRows.length === 0 ? (
              <div className="py-16 text-center text-slate-500">
                <div className="text-2xl">📭</div>
                <div className="mt-4 text-lg font-semibold">No progress records</div>
                <div className="mt-2 text-sm">No teacher exam entries found for the selected filters.</div>
              </div>
            ) : (
              <>
                <div className="space-y-3 md:hidden">
                  {progressRows.map((row, idx) => {
                    const rowEntry = getRequiredEntryInfo(row);
                    return (
                      <article
                        key={`${row.teacherId}-${row.subjectId}-${row.className}-${row.month}`}
                        className={`overflow-hidden rounded-3xl border p-4 shadow-sm ${getCardTintClasses(row.completionPercent)}`}
                      >
                      <div className="flex items-start justify-between gap-4">
                        <div className="space-y-1">
                          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-600">{row.className}</p>
                          <p className="text-base font-semibold text-slate-900">{row.teacherName}</p>
                          <p className="text-sm text-slate-600">{row.subjectName || row.subjectId}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-3xl font-semibold tracking-tight">{rowEntry.displayPercent}%</p>
                          <span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${getStatusBadgeClasses(rowEntry.isComplete ? 'complete' : 'incomplete')}`}>
                            {rowEntry.isComplete ? 'Complete' : 'Incomplete'}
                          </span>
                        </div>
                      </div>
                      <div className="mt-4 space-y-3">
                        <div className="flex flex-wrap gap-2 text-xs text-slate-600">
                          <span className="rounded-2xl bg-white/90 px-3 py-2">{row.month}</span>
                          <span className="rounded-2xl bg-white/90 px-3 py-2">{row.completedEntries}/{row.requiredEntries} entered</span>
                          <span className="rounded-2xl bg-white/90 px-3 py-2">Class size {row.totalStudents || '—'}</span>
                        </div>
                        <div className="space-y-2">
                          <div className="flex items-center justify-between text-[11px] uppercase tracking-[0.25em] text-slate-500">
                            <span>Progress</span>
                            <span>{row.completionPercent}%</span>
                          </div>
                          <div className="h-2 overflow-hidden rounded-full bg-slate-200">
                            <div
                              className={`h-full rounded-full ${rowEntry.isComplete ? 'bg-emerald-500' : 'bg-amber-500'}`}
                              style={{ width: `${rowEntry.displayPercent}%` }}
                            />
                          </div>
                        </div>
                        <div className="flex items-center justify-between gap-3">
                          <button
                            type="button"
                            onClick={() => setSelectedDetail(row)}
                            className="flex-1 rounded-2xl border border-slate-200 bg-white/95 px-3 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-100"
                          >
                            View details
                          </button>
                          <button className="inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-slate-200 bg-white text-slate-700 shadow-sm">
                            🔔
                          </button>
                        </div>
                      </div>
                    </article>
                  );
                })}
                </div>

                <div className="hidden md:block overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead>
                      <tr className="border-b border-slate-200 text-slate-600">
                        <th className="px-3 py-3">#</th>
                        <th className="px-3 py-3">Teacher</th>
                        <th className="px-3 py-3">Class</th>
                        <th className="px-3 py-3">Subject</th>
                        <th className="px-3 py-3">Month</th>
                        <th className="px-3 py-3">Progress</th>
                        <th className="px-3 py-3">Status</th>
                        <th className="px-3 py-3">Missing Entries</th>
                        <th className="px-3 py-3">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {progressRows.map((row, idx) => {
                        const rowEntry = getRequiredEntryInfo(row);
                        return (
                          <tr key={`${row.teacherId}-${row.subjectId}-${row.className}-${row.month}`} className="border-b border-slate-100 last:border-none">
                          <td className="px-3 py-3 text-slate-700">{idx + 1}</td>
                          <td className="px-3 py-3 text-slate-900 font-medium">{row.teacherName}</td>
                          <td className="px-3 py-3 text-slate-700">{row.className}</td>
                          <td className="px-3 py-3 text-slate-700">{row.subjectName || row.subjectId}</td>
                          <td className="px-3 py-3 text-slate-700">{row.month}</td>
                          <td className="px-3 py-3">
                            <div className="mb-2 text-xs text-slate-500">{row.completedEntries}/{row.requiredEntries} entered</div>
                            <div className="h-2 w-full overflow-hidden rounded-full bg-slate-200">
                              <div
                                className={`h-full rounded-full ${rowEntry.isComplete ? 'bg-emerald-500' : 'bg-amber-500'}`}
                                style={{ width: `${rowEntry.displayPercent}%` }}
                              />
                            </div>
                            <div className="text-xs mt-1">{rowEntry.displayPercent}%</div>
                          </td>
                          <td className="px-3 py-3">
                            <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${rowEntry.isComplete ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                              {rowEntry.isComplete ? '✅ Complete' : '⚠️ Incomplete'}
                            </span>
                          </td>
                          <td className="px-3 py-3">
                            {row.missingExamTypes && row.missingExamTypes.length > 0 ? (
                              <div className="flex flex-col gap-1">
                                {row.missingExamTypes.map(type => (
                                  <span key={type} className="rounded-full bg-rose-50 px-2 py-1 text-[11px] font-medium text-rose-700">CA: {type}</span>
                                ))}
                              </div>
                            ) : (
                              <span className="text-xs text-slate-500">✓ All submitted</span>
                            )}
                          </td>
                          <td className="px-3 py-3 text-right">
                            <button
                              type="button"
                              onClick={() => setSelectedDetail(row)}
                              className="rounded-2xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100"
                            >
                              View
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                    </tbody>
                  </table>
                </div>
              </>
            )}
            {selectedDetail && (
              <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/30 p-4">
                <div className="w-full max-w-md max-h-[calc(100vh-2rem)] overflow-y-auto rounded-3xl bg-white shadow-2xl">
                  <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4">
                    <div>
                      <p className="text-xs uppercase tracking-[0.28em] text-slate-500">Entry details</p>
                      <p className="mt-1 text-lg font-semibold text-slate-900">{selectedDetail.className} • {selectedDetail.teacherName}</p>
                    </div>
                    <button
                      type="button"
                      onClick={() => setSelectedDetail(null)}
                      className="rounded-full border border-slate-200 bg-slate-100 px-3 py-1 text-sm text-slate-700 hover:bg-slate-200"
                    >
                      Close
                    </button>
                  </div>
                  <div className="space-y-4 px-5 py-5 text-sm text-slate-700">
                    <div className="grid gap-3 sm:grid-cols-2">
                      <DetailCard label="Subject" value={selectedDetail.subjectName || selectedDetail.subjectId} />
                      <DetailCard label="Month" value={selectedDetail.month} />
                    </div>
                    <div className="rounded-3xl bg-slate-50 p-4">
                      <div className="flex items-center justify-between text-xs uppercase tracking-[0.28em] text-slate-500">
                        <span>Completion</span>
                        <span>{selectedDetail.completionPercent}%</span>
                      </div>
                      <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200">
                        <div
                          className={`h-full rounded-full ${selectedDetail.completionPercent === 100 ? 'bg-emerald-500' : 'bg-amber-500'}`}
                          style={{ width: `${selectedDetail.completionPercent}%` }}
                        />
                      </div>
                    </div>
                    <div className="grid gap-3 sm:grid-cols-2">
                      <DetailCard label="CA entered" value={selectedDetail.caEntered} />
                      <DetailCard label="Homework entered" value={selectedDetail.homeworkEntered} />
                      <DetailCard label="Classwork entered" value={selectedDetail.classworkEntered} />
                      <DetailCard label="Attendance entered" value={selectedDetail.attendanceEntered} />
                      <DetailCard label="Quiz entered" value={selectedDetail.quizEntered} />
                      <DetailCard label="Class size" value={selectedDetail.totalStudents} />
                    </div>
                    {(() => {
                      const entryInfo = getRequiredEntryInfo(selectedDetail);
                      return (
                        <div className="rounded-3xl bg-slate-100 p-4 text-sm text-slate-600">
                          <p className="font-semibold text-slate-900">Required entries</p>
                          <p className="mt-2">{entryInfo.completedCount} of {entryInfo.requiredCount} items entered</p>
                          <p className="mt-2 text-xs text-slate-500">Required: {entryInfo.requiredItems.join(' + ')}</p>
                          <p className="mt-1 text-xs text-slate-500">Completed: {entryInfo.completedItems.length > 0 ? entryInfo.completedItems.join(', ') : 'None'}</p>
                        </div>
                      );
                    })()}
                  </div>
                </div>
              </div>
            )}
          </>
        )}

        {activeTab === 'heat' && (
          <div>
            <h3 className="text-lg font-semibold mb-3">Heat Map (Teacher × Subject)</h3>
            <HeatMap
              month={selectedMonth}
              classNames={selectedClass ? [selectedClass] : supervisorClasses}
            />
          </div>
        )}

        {activeTab === 'notify' && (
          <div>
            <h3 className="text-lg font-semibold mb-3">Notify Teachers</h3>
            {progressRows.length === 0 ? (
              <div className="py-16 text-center text-slate-500">
                <div className="text-2xl">📭</div>
                <div className="mt-4 text-lg font-semibold">No teachers require follow-up</div>
                <div className="mt-2 text-sm">All teachers have submitted required entries for the selected filters.</div>
              </div>
            ) : (
              <>
                <div className="flex gap-3 mb-4">
                  <button className="px-4 py-2 rounded bg-emerald-500 text-white" onClick={() => notifyAllTeachers(progressRows)}>Notify All ({kpis.incomplete})</button>
                  <button className="px-4 py-2 rounded bg-slate-100" onClick={() => console.log('Open template editor')}>Edit Template</button>
                </div>
                <div className="space-y-3">
                  {Array.from(new Map(progressRows.map(r => [r.teacherId, r]))).map(([tid, row]) => (
                    <div key={tid} className="flex items-center justify-between bg-white p-3 rounded shadow-sm">
                      <div>
                        <div className="font-medium">{row.teacherName}</div>
                        <div className="text-xs text-slate-500">{row.className} • {row.subjectName || row.subjectId}</div>
                      </div>
                      <div className="flex gap-2">
                        <button className="px-3 py-1 rounded bg-amber-500 text-white" onClick={() => notifyTeacher(row.teacherId)}>Notify</button>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>
        )}

        {activeTab === 'sql' && (
          <div>
            <h3 className="text-lg font-semibold mb-3">SQL / API Reference</h3>
            <div className="text-xs text-slate-600 mb-2">Showing {progressRows.length} records</div>
            <pre className="bg-slate-50 p-3 rounded text-xs overflow-auto">GET /rest/v1/teacher_exam_progress?month=eq.{selectedMonth}</pre>
            <div className="mt-3 text-sm text-slate-500">You can also query the fallback data via the `exams` and `class_subjects` tables.</div>
          </div>
        )}
      </div>
    </div>
  );
}

function DetailCard({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="rounded-3xl bg-slate-50 p-4">
      <p className="text-[11px] uppercase tracking-[0.28em] text-slate-500">{label}</p>
      <p className="mt-2 text-lg font-semibold text-slate-900">{value}</p>
    </div>
  );
}
