// Generated by Copilot
import { useState } from 'react';
import { ExamVerification } from '../admin/ExamVerification';
import { ExamReport } from '../reports/ExamReport';

export function SupervisorDashboard() {
  const [tab, setTab] = useState<'verifications' | 'reports'>('verifications');

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Supervisor Dashboard</h1>
        <p className="text-slate-500 mt-1">Overview: exam verifications and reports</p>
      </div>

      <div className="flex gap-2">
        <button onClick={() => setTab('verifications')}
          className={`px-4 py-2 rounded-xl text-sm font-medium ${tab === 'verifications' ? 'bg-amber-100 text-amber-700' : 'bg-white text-slate-600 border border-slate-200'}`}>
          Verifications
        </button>
        <button onClick={() => setTab('reports')}
          className={`px-4 py-2 rounded-xl text-sm font-medium ${tab === 'reports' ? 'bg-indigo-100 text-indigo-700' : 'bg-white text-slate-600 border border-slate-200'}`}>
          Reports
        </button>
      </div>

      <div>
        {tab === 'verifications' ? <ExamVerification /> : <ExamReport />}
      </div>
    </div>
  );
}
