import { useState, useEffect } from 'react';
import { Listbox } from '@headlessui/react';
import { getStudentsPaginated, getStudentsByClasses, getUsersByRole, createStudent, updateStudent, deleteStudent, getExamsByStudent, getStudentById, getReportCommentsForStudentTerm, getCurrentTerm } from '../../lib/database';
import { Student, User, CLASSES, Exam } from '../../types';
import { useToast } from '../../context/ToastContext';
import { Dialog } from '../../components/ui/Dialog';
import { ExamReport } from '../reports/ExamReport';
import { DataTable } from '../../components/ui/DataTable';
import { Plus, Trash2, Edit, GraduationCap, Search, ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '../../utils/cn';
import { ColumnDef } from '@tanstack/react-table';

export function ManageStudents() {
  // Generated by Copilot
  const { addToast } = useToast();
  const [students, setStudents] = useState<Student[]>([]);
  const [totalStudents, setTotalStudents] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [parents, setParents] = useState<User[]>([]);
  const [classFilter, setClassFilter] = useState<string[]>([]); // empty = all classes
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [showEdit, setShowEdit] = useState<Student | null>(null);
  const [showExamDialog, setShowExamDialog] = useState(false);
  const [examStudentId, setExamStudentId] = useState<string | null>(null);
  const [examEntries, setExamEntries] = useState<Exam[]>([]);
  const [examLoading, setExamLoading] = useState(false);
  const [examReportComments, setExamReportComments] = useState<Record<string, string>>({});

  useEffect(() => {
    if (!showExamDialog || !examStudentId) return;
    let mounted = true;
    const loadExams = async () => {
      setExamLoading(true);
      try {
        const exams = await getExamsByStudent(examStudentId);
        if (!mounted) return;
        setExamEntries(exams || []);

        // Try to fetch report comments for the current term
        const term = await getCurrentTerm();
        if (term) {
          const comments = await getReportCommentsForStudentTerm(examStudentId, term.id);
          const map: Record<string, string> = {};
          for (const c of comments) {
            if (c.examId && c.teacherComment) map[c.examId] = c.teacherComment;
          }
          if (!mounted) return;
          setExamReportComments(map);
        } else {
          setExamReportComments({});
        }
      } catch (err) {
        setExamEntries([]);
        setExamReportComments({});
      } finally {
        if (mounted) setExamLoading(false);
      }
    };
    loadExams();
    return () => { mounted = false; };
  }, [showExamDialog, examStudentId]);

  const [formName, setFormName] = useState('');
  const [formClass, setFormClass] = useState(CLASSES[0]);
  const [formParent, setFormParent] = useState('');
  const [parentSearch, setParentSearch] = useState('');
  const [parentFocused, setParentFocused] = useState(false);

  const STUDENTS_PER_PAGE = 50;

  const refresh = async (page: number = currentPage, searchTerm?: string) => {
    const term = searchTerm || search || '';
    // If class filter is active, fetch all students for those classes (with optional search)
    if (classFilter.length > 0) {
      const [studentsData, parentsData] = await Promise.all([
        getStudentsByClasses(classFilter, term),
        getUsersByRole('parent')
      ]);
      setStudents(studentsData);
      setTotalStudents(studentsData.length);
      setParents(parentsData);
      return;
    }

    const [studentsData, parentsData] = await Promise.all([
      getStudentsPaginated(page, STUDENTS_PER_PAGE, term),
      getUsersByRole('parent')
    ]);
    setStudents(studentsData.students);
    setTotalStudents(studentsData.total);
    setParents(parentsData);
  };

  useEffect(() => {
    refresh();
  }, [currentPage]);

  // Debounce search input (wait until user stops typing)
  useEffect(() => {
    const t = setTimeout(() => setDebouncedSearch(search.trim()), 350);
    return () => clearTimeout(t);
  }, [search]);

  useEffect(() => {
    setCurrentPage(1);
    refresh(1, debouncedSearch);
  }, [debouncedSearch]);

  useEffect(() => {
    // When class filter changes, reload using current debouncedSearch
    setCurrentPage(1);
    refresh(1, debouncedSearch);
  }, [classFilter]);

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  const filteredParents = parents.filter(p =>
    p.name.toLowerCase().includes(parentSearch.toLowerCase()) ||
    p.email.toLowerCase().includes(parentSearch.toLowerCase())
  );

  const filtered = students.filter(s => classFilter.length === 0 || classFilter.includes(s.className));

  const columns: ColumnDef<Student>[] = [
    {
      accessorKey: 'name',
      header: 'Name',
      cell: ({ row }) => {
        const student = row.original;
        return (
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold text-xs">
              {student.name.split(' ').map(n => n[0]).join('')}
            </div>
            <span className="font-medium text-gray-900">{student.name}</span>
          </div>
        );
      },
    },
    {
      accessorKey: 'className',
      header: 'Class',
      cell: ({ row }) => {
        const className = row.getValue('className') as string;
        return (
          <span className="bg-indigo-50 text-indigo-700 px-2.5 py-1 rounded-lg text-xs font-semibold">
            {className}
          </span>
        );
      },
    },
    {
      id: 'parent',
      header: 'Parent',
      cell: ({ row }) => {
        const student = row.original;
        const parent = parents.find(p => p.id === student.parentId);
        return parent ? (
          <div>
            <span className="text-sm text-gray-900 font-medium">{parent.name}</span>
            {parent.phone1 && <span className="text-xs text-gray-500 block">{parent.phone1}</span>}
          </div>
        ) : (
          <span className="text-sm text-gray-400 italic">Unassigned</span>
        );
      },
    },
    {
      id: 'actions',
      header: 'Actions',
      cell: ({ row }) => {
        const student = row.original;
        return (
          <div className="flex items-center gap-2">
            <button
              onClick={() => { setExamStudentId(student.id); setShowExamDialog(true); }}
              title="View Exam Entry"
              className="p-1 text-slate-500 hover:text-slate-700"
            >
              <Search className="w-4 h-4" />
            </button>
            <button
              onClick={() => openEdit(student)}
              className="p-1 text-blue-400 hover:text-blue-600"
            >
              <Edit className="w-4 h-4" />
            </button>
            <button
              onClick={() => handleDelete(student)}
              className="p-1 text-red-400 hover:text-red-600"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        );
      },
    },
  ];

  const resetForm = () => { setFormName(''); setFormClass(CLASSES[0]); setFormParent(''); setParentSearch(''); };

  const handleCreate = async () => {
    if (!formName.trim()) { addToast({ type: 'error', title: 'Student name is required' }); return; }
    try {
      await createStudent({ name: formName, className: formClass, parentId: formParent || null });
      addToast({ type: 'success', title: 'Student added successfully' });
      resetForm(); setShowCreate(false); await refresh();
    } catch (error) {
      addToast({ type: 'error', title: 'Failed to add student' });
    }
  };

  const handleEdit = async () => {
    if (!showEdit) return;
    try {
      await updateStudent(showEdit.id, { name: formName, className: formClass, parentId: formParent || null });
      addToast({ type: 'success', title: 'Student updated' });
      resetForm(); setShowEdit(null); await refresh();
    } catch (error) {
      addToast({ type: 'error', title: 'Failed to update student' });
    }
  };

  const handleDelete = async (s: Student) => {
    try {
      await deleteStudent(s.id);
      addToast({ type: 'success', title: `${s.name} deleted` });
      await refresh();
    } catch (error) {
      addToast({ type: 'error', title: 'Failed to delete student' });
    }
  };

  const openEdit = (s: Student) => {
    const parent = parents.find(p => p.id === s.parentId);
    setFormName(s.name);
    setFormClass(s.className);
    setFormParent(s.parentId || '');
    setParentSearch(parent ? parent.name : '');
    setShowEdit(s);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Manage Students</h1>
          <p className="text-slate-500 mt-1">Add students, assign classes and parents</p>
        </div>
        <button onClick={() => { resetForm(); setShowCreate(true); }}
          className="flex items-center gap-2 px-4 py-2.5 bg-indigo-600 text-white rounded-xl font-medium text-sm hover:bg-indigo-700 shadow-lg shadow-indigo-200 transition-all">
          <Plus className="w-4 h-4" /> Add Student
        </button>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative">
          <Listbox value={classFilter} onChange={(v: any) => {
            // v will be an array of selected values when `multiple` is true
            if (Array.isArray(v)) {
              // sentinel value to represent All Classes
              if (v.includes('__ALL__')) {
                setClassFilter([]);
              } else {
                setClassFilter(v as string[]);
              }
            } else {
              // fallback: single value
              if (v === '__ALL__') setClassFilter([]);
              else setClassFilter([v]);
            }
          }} multiple>
            <div className="relative">
              <Listbox.Button className="w-60 text-left px-4 py-2 rounded-xl border border-slate-200 bg-white text-sm flex items-center justify-between">
                <span className="truncate text-slate-700">
                  {classFilter.length === 0 ? 'All Classes' : classFilter.join(', ')}
                </span>
                <svg className="w-4 h-4 text-slate-400" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
                  <path d="M6 8l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </Listbox.Button>
              <Listbox.Options className="absolute mt-2 z-20 w-60 max-h-56 overflow-auto bg-white border border-slate-200 rounded-xl p-2 shadow">
                <Listbox.Option key="__all" value="__ALL__" className={({ active }) => `px-3 py-2 rounded-lg text-sm cursor-pointer ${active ? 'bg-slate-50' : ''}`}>
                  {() => (
                    <div className="flex items-center gap-3">
                      <input type="checkbox" readOnly checked={classFilter.length === 0} className="w-4 h-4" />
                      <span className={cn('truncate', classFilter.length === 0 ? 'font-semibold' : 'text-slate-700')}>All Classes</span>
                    </div>
                  )}
                </Listbox.Option>
                {CLASSES.map(cls => (
                  <Listbox.Option key={cls} value={cls} className={({ active }) => `px-3 py-2 rounded-lg text-sm cursor-pointer ${active ? 'bg-slate-50' : ''}`}>
                    {({ selected }) => (
                      <div className="flex items-center gap-3">
                        <input type="checkbox" readOnly checked={classFilter.includes(cls)} className="w-4 h-4" />
                        <span className={cn('truncate', selected ? 'font-semibold' : 'text-slate-700')}>{cls}</span>
                      </div>
                    )}
                  </Listbox.Option>
                ))}
              </Listbox.Options>
            </div>
          </Listbox>
        </div>
        <div className="relative flex-1 max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input type="text" placeholder="Search students..."
            value={search} onChange={e => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none" />
        </div>
      </div>



      {/* Students Table */}
      <DataTable
        data={filtered}
        columns={columns}
        searchPlaceholder="Search students..."
        searchValue={search}
        onSearchChange={setSearch}
      />

      {filtered.length === 0 && (
        <div className="text-center py-12 text-slate-400">
          <GraduationCap className="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">No students found</p>
        </div>
      )}

      {/* Create Dialog */}
      <Dialog open={showCreate} onClose={() => setShowCreate(false)} title="Add New Student" description="Only admins can add students">
        <div className="space-y-4">
          <input placeholder="Student Name" value={formName} onChange={e => setFormName(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none" />
          <div>
            <label className="text-sm font-semibold text-slate-700 mb-1.5 block">Class</label>
            <select value={formClass} onChange={e => setFormClass(e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none bg-white">
              {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div>
            <label className="text-sm font-semibold text-slate-700 mb-1.5 block">Assign Parent</label>
            <div className="relative">
              <input
                type="text"
                placeholder="Search parents by name or email..."
                value={parentSearch}
                onChange={e => setParentSearch(e.target.value)}
                onFocus={() => setParentFocused(true)}
                onBlur={() => setTimeout(() => setParentFocused(false), 150)}
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none"
              />
              {parentSearch && parentFocused && (
                <div className="mt-2 w-full bg-white border border-slate-200 rounded-xl shadow-lg max-h-48 overflow-y-auto">
                  <button
                    onClick={() => { setFormParent(''); setParentSearch(''); }}
                    className="w-full px-4 py-2 text-left text-sm text-slate-500 hover:bg-slate-50"
                  >
                    — No parent —
                  </button>
                  {filteredParents.map(p => (
                    <button
                      key={p.id}
                      onClick={() => { setFormParent(p.id); setParentSearch(p.name); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50"
                    >
                      <div className="font-medium text-slate-800">{p.name}</div>
                      <div className="text-xs text-slate-500">{p.email}</div>
                    </button>
                  ))}
                  {filteredParents.length === 0 && parentSearch && (
                    <div className="px-4 py-2 text-sm text-slate-500">No parents found</div>
                  )}
                </div>
              )}
            </div>
          </div>
          <button onClick={handleCreate}
            className="w-full py-2.5 bg-indigo-600 text-white rounded-xl font-medium text-sm hover:bg-indigo-700 transition-colors">
            Add Student
          </button>
        </div>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={!!showEdit} onClose={() => { setShowEdit(null); resetForm(); }} title="Edit Student">
        <div className="space-y-4">
          <input placeholder="Student Name" value={formName} onChange={e => setFormName(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none" />
          <div>
            <label className="text-sm font-semibold text-slate-700 mb-1.5 block">Class</label>
            <select value={formClass} onChange={e => setFormClass(e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none bg-white">
              {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div>
            <label className="text-sm font-semibold text-slate-700 mb-1.5 block">Assign Parent</label>
            <div className="relative">
              <input
                type="text"
                placeholder="Search parents by name or email..."
                value={parentSearch}
                onChange={e => setParentSearch(e.target.value)}
                onFocus={() => setParentFocused(true)}
                onBlur={() => setTimeout(() => setParentFocused(false), 150)}
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-200 focus:border-indigo-400 outline-none"
              />
              {parentSearch && parentFocused && (
                <div className="mt-2 w-full bg-white border border-slate-200 rounded-xl shadow-lg max-h-48 overflow-y-auto">
                  <button
                    onClick={() => { setFormParent(''); setParentSearch(''); }}
                    className="w-full px-4 py-2 text-left text-sm text-slate-500 hover:bg-slate-50"
                  >
                    — No parent —
                  </button>
                  {filteredParents.map(p => (
                    <button
                      key={p.id}
                      onClick={() => { setFormParent(p.id); setParentSearch(p.name); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50"
                    >
                      <div className="font-medium text-slate-800">{p.name}</div>
                      <div className="text-xs text-slate-500">{p.email}</div>
                    </button>
                  ))}
                  {filteredParents.length === 0 && parentSearch && (
                    <div className="px-4 py-2 text-sm text-slate-500">No parents found</div>
                  )}
                </div>
              )}
            </div>
          </div>
          <button onClick={handleEdit}
            className="w-full py-2.5 bg-indigo-600 text-white rounded-xl font-medium text-sm hover:bg-indigo-700 transition-colors">
            Save Changes
          </button>
        </div>
      </Dialog>
      {/* Exam Entry Dialog */}
      <Dialog open={showExamDialog} onClose={() => { setShowExamDialog(false); setExamStudentId(null); setExamEntries([]); setExamReportComments({}); }} title="Exam Entries">
        <div className="w-full h-[70vh] overflow-auto">
          {/* Load and show each exam entry for the selected student */}
          <ExamEntriesDialogContent
            studentId={examStudentId}
            entries={examEntries}
            loading={examLoading}
            reportComments={examReportComments}
          />
        </div>
      </Dialog>
    </div>
  );
}

function ExamEntriesDialogContent({ studentId, entries, loading, reportComments }: { studentId: string | null; entries: Exam[]; loading: boolean; reportComments: Record<string, string> }) {
  const [studentName, setStudentName] = useState<string>('');

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      if (!studentId) return;
      try {
        const s = await getStudentById(studentId);
        if (!mounted) return;
        setStudentName(s?.name || 'Student');
      } catch (err) {
        // ignore
      }
    };
    load();
    return () => { mounted = false; };
  }, [studentId]);

  const rows = entries.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-semibold">{studentName} — Exam Entries</h3>
        <p className="text-sm text-slate-500">Showing individual exam records for the selected student</p>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200">
        {loading ? (
          <div className="p-6 text-center text-slate-500">Loading...</div>
        ) : rows.length === 0 ? (
          <div className="text-center py-12 text-slate-400">
            <GraduationCap className="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p className="font-medium">No exam entries found for this student</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="text-left px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Subject</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Type</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Month</th>
                  <th className="text-center px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Score</th>
                  <th className="text-center px-5 py-3 text-xs font-semibold text-slate-500 uppercase">%</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Status</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-slate-500 uppercase">Teacher Comment</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {rows.map(e => {
                  const pct = e.total > 0 ? Math.round((e.score / e.total) * 100) : 0;
                  return (
                    <tr key={e.id} className="hover:bg-slate-50 transition-colors">
                      <td className="px-5 py-3 text-sm text-slate-700">{e.subject}</td>
                      <td className="px-5 py-3 text-sm text-slate-600">{e.examType}</td>
                      <td className="px-5 py-3 text-sm text-slate-600">{e.month}</td>
                      <td className="px-5 py-3 text-center font-bold text-sm text-slate-800">{e.score}/{e.total}</td>
                      <td className="px-5 py-3 text-center"><span className={cn('text-sm font-bold', pct >= 80 ? 'text-emerald-600' : pct >= 60 ? 'text-amber-600' : 'text-red-600')}>{pct}%</span></td>
                      <td className="px-5 py-3 text-sm text-slate-600">{e.status}</td>
                      <td className="px-5 py-3 text-sm text-slate-600">{reportComments[e.id] || '—'}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
