// Generated by Copilot
import { useEffect, useMemo, useState } from 'react';
import {
  getSubjects, createSubject, updateSubject, deleteSubject,
  getAcademicYears, createAcademicYear, updateAcademicYear, deleteAcademicYear,
  getTerms, createTerm, updateTerm, deleteTerm,
} from '../../lib/database';
import { Subject, AcademicYear, Term } from '../../types';
import { useToast } from '../../context/ToastContext';
import { DataTable } from '../../components/ui/DataTable';
import { Dialog } from '../../components/ui/Dialog';
import { Plus, Pencil, Trash2 } from 'lucide-react';

export function ManageAcademic() {
  const { addToast } = useToast();
  const [activeTab, setActiveTab] = useState<'subjects' | 'years' | 'terms'>('subjects');

  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [years, setYears] = useState<AcademicYear[]>([]);
  const [terms, setTerms] = useState<Term[]>([]);

  const [showForm, setShowForm] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  const [formName, setFormName] = useState('');
  const [formShortName, setFormShortName] = useState('');
  const [formAcademicYearId, setFormAcademicYearId] = useState<string>('');
  const [formStartDate, setFormStartDate] = useState('');
  const [formEndDate, setFormEndDate] = useState('');
  const [formIsCurrent, setFormIsCurrent] = useState(false);

  const [currentItemId, setCurrentItemId] = useState<string>('');

  const fetchData = async () => {
    try {
      const [s, y, t] = await Promise.all([getSubjects(), getAcademicYears(), getTerms()]);
      setSubjects(s);
      setYears(y);
      setTerms(t);
    } catch (error) {
      addToast({ type: 'error', title: 'Failed to fetch academic lists' });
    }
  };

  useEffect(() => { fetchData(); }, []);

  const resetForm = () => {
    setFormName('');
    setFormShortName('');
    setFormAcademicYearId('');
    setFormStartDate('');
    setFormEndDate('');
    setFormIsCurrent(false);
    setCurrentItemId('');
    setIsEditing(false);
  };

  const openNew = () => { resetForm(); setShowForm(true); };

  const openEdit = (id: string, payload: {
    name: string;
    shortName?: string;
    academicYearId?: string;
    startDate?: string;
    endDate?: string;
    isCurrent?: boolean;
  }) => {
    setIsEditing(true);
    setCurrentItemId(id);
    setFormName(payload.name);
    setFormShortName(payload.shortName || '');
    setFormAcademicYearId(payload.academicYearId || '');
    setFormStartDate(payload.startDate || '');
    setFormEndDate(payload.endDate || '');
    setFormIsCurrent(!!payload.isCurrent);
    setShowForm(true);
  };

  const handleSave = async () => {
    try {
      if (activeTab === 'subjects') {
        if (!formName.trim()) { addToast({ type: 'error', title: 'Subject name required' }); return; }
        const payload = { name: formName, shortName: formShortName || undefined };

        if (isEditing) {
          await updateSubject(currentItemId, payload);
          addToast({ type: 'success', title: 'Subject updated' });
        } else {
          await createSubject(payload);
          addToast({ type: 'success', title: 'Subject created' });
        }
      } else if (activeTab === 'years') {
        if (!formName.trim() || !formStartDate || !formEndDate) {
          addToast({ type: 'error', title: 'Year name, start and end dates required' });
          return;
        }

        const payload = {
          name: formName,
          startDate: formStartDate,
          endDate: formEndDate,
          isCurrent: formIsCurrent,
        };

        if (isEditing) {
          await updateAcademicYear(currentItemId, payload);
          addToast({ type: 'success', title: 'Academic year updated' });
        } else {
          await createAcademicYear(payload);
          addToast({ type: 'success', title: 'Academic year added' });
        }
      } else {
        if (!formName.trim() || !formAcademicYearId || !formStartDate || !formEndDate) {
          addToast({ type: 'error', title: 'Term name, academic year, start and end dates required' });
          return;
        }

        const payload = {
          name: formName,
          academicYearId: formAcademicYearId,
          startDate: formStartDate,
          endDate: formEndDate,
          isCurrent: formIsCurrent,
          months: [],
        };

        if (isEditing) {
          await updateTerm(currentItemId, payload);
          addToast({ type: 'success', title: 'Term updated' });
        } else {
          await createTerm(payload);
          addToast({ type: 'success', title: 'Term created' });
        }
      }

      setShowForm(false);
      await fetchData();
      resetForm();
    } catch (error) {
      addToast({ type: 'error', title: 'Save operation failed' });
      console.error('ManageAcademic save error', error);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      if (activeTab === 'subjects') await deleteSubject(id);
      if (activeTab === 'years') await deleteAcademicYear(id);
      if (activeTab === 'terms') await deleteTerm(id);
      addToast({ type: 'success', title: 'Deleted successfully' });
      await fetchData();
    } catch (error) {
      addToast({ type: 'error', title: 'Delete failed' });
      console.error('ManageAcademic delete error', error);
    }
  };

  const columns = useMemo(() => {
    switch (activeTab) {
      case 'years':
        return [
          { accessorKey: 'name', header: 'Academic Year' },
          { accessorKey: 'startDate', header: 'Start' },
          { accessorKey: 'endDate', header: 'End' },
          { accessorKey: 'isCurrent', header: 'Current', cell: ({ row }: any) => row.original.isCurrent ? 'Yes' : 'No' },
          {
            id: 'actions',
            header: 'Actions',
            cell: ({ row }: any) => (
              <div className="flex gap-2">
                <button onClick={() => openEdit(row.original.id, {
                  name: row.original.name,
                  startDate: row.original.startDate,
                  endDate: row.original.endDate,
                  isCurrent: row.original.isCurrent,
                })} className="text-blue-500"><Pencil size={14} /></button>
                <button onClick={() => handleDelete(row.original.id)} className="text-red-500"><Trash2 size={14} /></button>
              </div>
            ),
          },
        ];
      case 'terms':
        return [
          { accessorKey: 'name', header: 'Term' },
          { accessorKey: 'academicYearId', header: 'Academic Year', cell: ({ row }: any) => row.original.academic_years?.name ?? row.original.academicYearId ?? '-' },
          { accessorKey: 'startDate', header: 'Start' },
          { accessorKey: 'endDate', header: 'End' },
          { accessorKey: 'isCurrent', header: 'Current', cell: ({ row }: any) => row.original.isCurrent ? 'Yes' : 'No' },
          {
            id: 'actions',
            header: 'Actions',
            cell: ({ row }: any) => (
              <div className="flex gap-2">
                <button onClick={() => openEdit(row.original.id, {
                  name: row.original.name,
                  academicYearId: row.original.academicYearId,
                  startDate: row.original.startDate,
                  endDate: row.original.endDate,
                  isCurrent: row.original.isCurrent,
                })} className="text-blue-500"><Pencil size={14} /></button>
                <button onClick={() => handleDelete(row.original.id)} className="text-red-500"><Trash2 size={14} /></button>
              </div>
            ),
          },
        ];
      default:
        return [
          { accessorKey: 'name', header: 'Subject' },
          { accessorKey: 'shortName', header: 'Short Name', cell: ({ row }: any) => row.original.shortName ?? '-' },
          {
            id: 'actions',
            header: 'Actions',
            cell: ({ row }: any) => (
              <div className="flex gap-2">
                <button onClick={() => openEdit(row.original.id, { name: row.original.name, shortName: row.original.shortName })} className="text-blue-500"><Pencil size={14} /></button>
                <button onClick={() => handleDelete(row.original.id)} className="text-red-500"><Trash2 size={14} /></button>
              </div>
            ),
          },
        ];
    }
  }, [activeTab, years]);

  const data = activeTab === 'years' ? years : activeTab === 'terms' ? terms : subjects;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Manage Academic</h1>
          <p className="text-slate-500">Maintain subjects, academic years, and terms</p>
        </div>
        <button onClick={openNew} className="px-4 py-2 rounded-xl bg-indigo-600 text-white hover:bg-indigo-700 flex items-center gap-2">
          <Plus size={16} /> Add {activeTab === 'years' ? 'Year' : activeTab === 'terms' ? 'Term' : 'Subject'}
        </button>
      </div>

      <div className="flex gap-2">
        {['subjects', 'years', 'terms'].map(tab => (
          <button key={tab} onClick={() => { setActiveTab(tab as any); resetForm(); }}
            className={`px-4 py-2 rounded-lg text-sm font-medium ${activeTab === tab ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600 border border-slate-200'}`}>
            {tab.charAt(0).toUpperCase() + tab.slice(1)}
          </button>
        ))}
      </div>

      <DataTable data={data as any} columns={columns as any} />

      <Dialog open={showForm} onClose={() => setShowForm(false)} title={`${isEditing ? 'Edit' : 'Add'} ${activeTab === 'years' ? 'Academic Year' : activeTab === 'terms' ? 'Term' : 'Subject'}`} description="" >
        <div className="space-y-3">
          <input value={formName} onChange={e => setFormName(e.target.value)} placeholder={activeTab === 'years' ? '2025/2026' : activeTab === 'terms' ? 'Term 1' : 'Mathematics'}
            className="w-full px-3 py-2 border border-slate-300 rounded-lg" />

          {activeTab === 'subjects' && (
            <input value={formShortName} onChange={e => setFormShortName(e.target.value)} placeholder="Short name (optional)"
              className="w-full px-3 py-2 border border-slate-300 rounded-lg" />
          )}

          {activeTab === 'years' && (
            <div className="space-y-2">
              <div className="grid grid-cols-2 gap-2">
                <input type="date" value={formStartDate} onChange={e => setFormStartDate(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg" />
                <input type="date" value={formEndDate} onChange={e => setFormEndDate(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg" />
              </div>
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={formIsCurrent} onChange={e => setFormIsCurrent(e.target.checked)} />
                Set as current academic year
              </label>
            </div>
          )}

          {activeTab === 'terms' && (
            <div className="space-y-2">
              <select value={formAcademicYearId} onChange={e => setFormAcademicYearId(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg">
                <option value="">Select academic year</option>
                {years.map(year => <option key={year.id} value={year.id}>{year.name}</option>)}
              </select>
              <div className="grid grid-cols-2 gap-2">
                <input type="date" value={formStartDate} onChange={e => setFormStartDate(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg" />
                <input type="date" value={formEndDate} onChange={e => setFormEndDate(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg" />
              </div>
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={formIsCurrent} onChange={e => setFormIsCurrent(e.target.checked)} />
                Set as current term
              </label>
            </div>
          )}

          <button onClick={handleSave} className="w-full px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">
            Save
          </button>
        </div>
      </Dialog>
    </div>
  );
}

