// Generated by Copilot
import React from 'react';

export const Skeleton: React.FC<{className?: string}> = ({ className = '' }) => {
  return (
    <div className={`animate-pulse bg-slate-100 ${className}`} />
  );
};

export default Skeleton;
